// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0x86c366a91393f3f8n;
export class StreamResult extends $.Struct {
  static readonly _capnp = {
    displayName: "StreamResult",
    id: "995f9a3377c0b16e",
    typeId: 0x995f9a3377c0b16en,
    typeIdHex: "995f9a3377c0b16e",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: StreamResult, value: $.Init<StreamResult>): void {
    const init = value;
  }
  toString(): string { return "StreamResult_" + super.toString(); }
}
