// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xe3fca095c1cb2e87n;
export class BigIntBag extends $.Struct {
  static readonly _capnp = {
    displayName: "BigIntBag",
    id: "86748469b18e4943",
    typeId: 0x86748469b18e4943n,
    typeIdHex: "86748469b18e4943",
    size: new $.ObjectSize(32, 0),
    fields: [
      { name: "signed", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "int64" } },
      { name: "unsigned", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "uint64" } },
      { name: "defaultSigned", codeOrder: 2, ordinal: 2, kind: "slot", offset: 2, type: { kind: "int64" } },
      { name: "defaultUnsigned", codeOrder: 3, ordinal: 3, kind: "slot", offset: 3, type: { kind: "uint64" } }
    ] as const,
    defaultDefaultSigned: $.getInt64Mask(-0xdb4da5f7ef412b1n),
    defaultDefaultUnsigned: $.getUint64Mask(0xdb4da5f7ef412b1n)
  };
  static _applyInit(target: BigIntBag, value: $.Init<BigIntBag>): void {
    const init = value as any;
    if (init["signed"] !== undefined) {
      target.signed = init["signed"] as any;
    }
    if (init["unsigned"] !== undefined) {
      target.unsigned = init["unsigned"] as any;
    }
    if (init["defaultSigned"] !== undefined) {
      target.defaultSigned = init["defaultSigned"] as any;
    }
    if (init["defaultUnsigned"] !== undefined) {
      target.defaultUnsigned = init["defaultUnsigned"] as any;
    }
  }
  get signed(): bigint {
    return $.utils.getInt64(0, this);
  }
  set signed(value: bigint) {
    $.utils.setInt64(0, value, this);
  }
  get unsigned(): bigint {
    return $.utils.getUint64(8, this);
  }
  set unsigned(value: bigint) {
    $.utils.setUint64(8, value, this);
  }
  get defaultSigned(): bigint {
    return $.utils.getInt64(16, this, BigIntBag._capnp.defaultDefaultSigned);
  }
  set defaultSigned(value: bigint) {
    $.utils.setInt64(16, value, this, BigIntBag._capnp.defaultDefaultSigned);
  }
  get defaultUnsigned(): bigint {
    return $.utils.getUint64(24, this, BigIntBag._capnp.defaultDefaultUnsigned);
  }
  set defaultUnsigned(value: bigint) {
    $.utils.setUint64(24, value, this, BigIntBag._capnp.defaultDefaultUnsigned);
  }
  toString(): string { return "BigIntBag_" + super.toString(); }
}
