// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xe0b7ff464fbc7ee2n;
export class Foo extends $.Struct {
  static readonly _capnp = {
    displayName: "Foo",
    id: "ebf41ad8c4cd4576",
    typeId: 0xebf41ad8c4cd4576n,
    typeIdHex: "ebf41ad8c4cd4576",
    size: new $.ObjectSize(0, 2),
    fields: [
      { name: "bar", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "baz", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "text" } }
    ] as const,
  };
  static _applyInit(target: Foo, value: $.Init<Foo>): void {
    const init = value as any;
    {
      const value = init["bar"];
      if (value !== undefined) {
        target.bar = value as any;
      }
    }
    {
      const value = init["baz"];
      if (value !== undefined) {
        target.baz = value as any;
      }
    }
  }
  get bar(): string {
    return $.utils.getText(0, this);
  }
  set bar(value: string) {
    $.utils.setText(0, value, this);
  }
  get baz(): string {
    return $.utils.getText(1, this);
  }
  set baz(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "Foo_" + super.toString(); }
}
