// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xe0b7ff464fbc7ee1n;
export class Foo extends $.Struct {
  static readonly _capnp = {
    displayName: "Foo",
    id: "9e8e6186e9348688",
    typeId: 0x9e8e6186e9348688n,
    typeIdHex: "9e8e6186e9348688",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "bar", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } }
    ] as const,
  };
  static _applyInit(target: Foo, value: $.Init<Foo>): void {
    const init = value as any;
    if (init["bar"] !== undefined) {
      target.bar = init["bar"] as any;
    }
  }
  get bar(): string {
    return $.utils.getText(0, this);
  }
  set bar(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "Foo_" + super.toString(); }
}
