// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xbba26a2caa3411e8n;
export class HashFactory_NewSha1$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "newSha1$Params",
    id: "82994ca98e892c55",
    typeId: 0x82994ca98e892c55n,
    typeIdHex: "82994ca98e892c55",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: HashFactory_NewSha1$Params, value: $.Init<HashFactory_NewSha1$Params>): void {
    const init = value;
  }
  toString(): string { return "HashFactory_NewSha1$Params_" + super.toString(); }
}
export class HashFactory_NewSha1$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "newSha1$Results",
    id: "9ad1223357407533",
    typeId: 0x9ad1223357407533n,
    typeIdHex: "9ad1223357407533",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "hash", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xe9620cda4245af9an, typeIdHex: "e9620cda4245af9a", displayName: "Hash" } }
    ] as const,
  };
  static _applyInit(target: HashFactory_NewSha1$Results, value: $.Init<HashFactory_NewSha1$Results>): void {
    const init = value;
    {
      const value = init["hash"];
      if (value !== undefined) {
        target.hash = value;
      }
    }
  }
  get hash(): Hash$Client {
    return new Hash$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  get hashOrNull(): Hash$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(0, this))?.getClient() ?? null;
    return client === null ? null : new Hash$Client(client);
  }
  set hashOrNull(value: Hash$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(0, this));
    }
    else {
      this.hash = value;
    }
  }
  set hash(value: Hash$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "HashFactory_NewSha1$Results_" + super.toString(); }
}
export class HashFactory_NewSha1$Results$Promise {
  pipeline: $.Pipeline<HashFactory_NewSha1$Results, $.Struct, HashFactory_NewSha1$Results>;
  constructor(pipeline: $.Pipeline<HashFactory_NewSha1$Results, $.Struct, HashFactory_NewSha1$Results>) {
    this.pipeline = pipeline;
  }
  getHash(): Hash$Client {
    return new Hash$Client(this.pipeline.getPipeline(Hash, 0).client());
  }
  async promise(): Promise<HashFactory_NewSha1$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = HashFactory_NewSha1$Results, TResult2 = never>(onfulfilled?: ((value: HashFactory_NewSha1$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null): Promise<HashFactory_NewSha1$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<HashFactory_NewSha1$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class HashFactory$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xcb1e6205ea21d707n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<HashFactory_NewSha1$Params, HashFactory_NewSha1$Results>
  ] = [
    {
      ParamsClass: HashFactory_NewSha1$Params,
      ResultsClass: HashFactory_NewSha1$Results,
      interfaceId: HashFactory$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/hash-factory.capnp:HashFactory",
      methodName: "newSha1",
      paramFields: HashFactory_NewSha1$Params._capnp.fields,
      resultFields: HashFactory_NewSha1$Results._capnp.fields
    }
  ];
  newSha1(): HashFactory_NewSha1$Results$Promise;
  newSha1(params: $.Init<HashFactory_NewSha1$Params>): HashFactory_NewSha1$Results$Promise;
  newSha1(paramsFunc: (params: HashFactory_NewSha1$Params) => void): HashFactory_NewSha1$Results$Promise;
  newSha1(params?: $.Initializer<HashFactory_NewSha1$Params>): HashFactory_NewSha1$Results$Promise {
    const answer = this.client.call({
      method: HashFactory$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: HashFactory_NewSha1$Params) => void
          : (target: HashFactory_NewSha1$Params) => HashFactory_NewSha1$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(HashFactory_NewSha1$Results, answer);
    return new HashFactory_NewSha1$Results$Promise(pipeline);
  }
}
$.Registry.register(HashFactory$Client.interfaceId, HashFactory$Client);
export interface HashFactory$Server$Target {
  newSha1(params: HashFactory_NewSha1$Params, results: HashFactory_NewSha1$Results): $.MaybePromise<void | $.Init<HashFactory_NewSha1$Results>>;
}
export class HashFactory$Server extends $.Server {
  readonly target: HashFactory$Server$Target;
  constructor(target: HashFactory$Server$Target) {
    super(target, [
      {
        ...HashFactory$Client.methods[0],
        impl: async (params: HashFactory_NewSha1$Params, results: HashFactory_NewSha1$Results) => {
          const value = await target.newSha1(params, results);
          if (value !== undefined) {
            HashFactory_NewSha1$Results._applyInit(results, value as $.Init<HashFactory_NewSha1$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): HashFactory$Client {
    return new HashFactory$Client(this);
  }
}
export class HashFactory extends $.Interface {
  static readonly Client = HashFactory$Client;
  static readonly Server = HashFactory$Server;
  static readonly _capnp = {
    displayName: "HashFactory",
    id: "cb1e6205ea21d707",
    typeId: 0xcb1e6205ea21d707n,
    typeIdHex: "cb1e6205ea21d707",
    size: new $.ObjectSize(0, 0),
    methods: HashFactory$Client.methods,
  };
  toString(): string { return "HashFactory_" + super.toString(); }
}
export class Hash_Write$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "write$Params",
    id: "f65501e064be5175",
    typeId: 0xf65501e064be5175n,
    typeIdHex: "f65501e064be5175",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "data", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "data" } }
    ] as const,
  };
  static _applyInit(target: Hash_Write$Params, value: $.Init<Hash_Write$Params>): void {
    const init = value;
    {
      const value = init["data"];
      if (value !== undefined) {
        if (value instanceof $.Data) {
          target.data = value;
        }
        else {
          const bytes = $.dataBytes(value);
          target._initData(bytes.byteLength).copyBuffer(bytes);
        }
      }
    }
  }
  _adoptData(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData(): $.Orphan<$.Data> {
    return $.utils.disown(this.data);
  }
  get data(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasData(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set data(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "Hash_Write$Params_" + super.toString(); }
}
export class Hash_Write$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "write$Results",
    id: "dffb54fe160f874c",
    typeId: 0xdffb54fe160f874cn,
    typeIdHex: "dffb54fe160f874c",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: Hash_Write$Results, value: $.Init<Hash_Write$Results>): void {
    const init = value;
  }
  toString(): string { return "Hash_Write$Results_" + super.toString(); }
}
export class Hash_Write$Results$Promise {
  pipeline: $.Pipeline<Hash_Write$Results, $.Struct, Hash_Write$Results>;
  constructor(pipeline: $.Pipeline<Hash_Write$Results, $.Struct, Hash_Write$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<Hash_Write$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = Hash_Write$Results, TResult2 = never>(onfulfilled?: ((value: Hash_Write$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null): Promise<Hash_Write$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<Hash_Write$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class Hash_Sum$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "sum$Params",
    id: "b494960a8116663b",
    typeId: 0xb494960a8116663bn,
    typeIdHex: "b494960a8116663b",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: Hash_Sum$Params, value: $.Init<Hash_Sum$Params>): void {
    const init = value;
  }
  toString(): string { return "Hash_Sum$Params_" + super.toString(); }
}
export class Hash_Sum$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "sum$Results",
    id: "e9098d3e3e6517b0",
    typeId: 0xe9098d3e3e6517b0n,
    typeIdHex: "e9098d3e3e6517b0",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "hash", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "data" } }
    ] as const,
  };
  static _applyInit(target: Hash_Sum$Results, value: $.Init<Hash_Sum$Results>): void {
    const init = value;
    {
      const value = init["hash"];
      if (value !== undefined) {
        if (value instanceof $.Data) {
          target.hash = value;
        }
        else {
          const bytes = $.dataBytes(value);
          target._initHash(bytes.byteLength).copyBuffer(bytes);
        }
      }
    }
  }
  _adoptHash(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHash(): $.Orphan<$.Data> {
    return $.utils.disown(this.hash);
  }
  get hash(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasHash(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHash(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set hash(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "Hash_Sum$Results_" + super.toString(); }
}
export class Hash_Sum$Results$Promise {
  pipeline: $.Pipeline<Hash_Sum$Results, $.Struct, Hash_Sum$Results>;
  constructor(pipeline: $.Pipeline<Hash_Sum$Results, $.Struct, Hash_Sum$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<Hash_Sum$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = Hash_Sum$Results, TResult2 = never>(onfulfilled?: ((value: Hash_Sum$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null): Promise<Hash_Sum$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<Hash_Sum$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class Hash$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xe9620cda4245af9an;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<Hash_Write$Params, Hash_Write$Results>,
    $.Method<Hash_Sum$Params, Hash_Sum$Results>
  ] = [
    {
      ParamsClass: Hash_Write$Params,
      ResultsClass: Hash_Write$Results,
      interfaceId: Hash$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/hash-factory.capnp:Hash",
      methodName: "write",
      paramFields: Hash_Write$Params._capnp.fields,
      resultFields: Hash_Write$Results._capnp.fields
    },
    {
      ParamsClass: Hash_Sum$Params,
      ResultsClass: Hash_Sum$Results,
      interfaceId: Hash$Client.interfaceId,
      methodId: 1,
      interfaceName: "test/fixtures/hash-factory.capnp:Hash",
      methodName: "sum",
      paramFields: Hash_Sum$Params._capnp.fields,
      resultFields: Hash_Sum$Results._capnp.fields
    }
  ];
  write(): Hash_Write$Results$Promise;
  write(params: $.Init<Hash_Write$Params>): Hash_Write$Results$Promise;
  write(paramsFunc: (params: Hash_Write$Params) => void): Hash_Write$Results$Promise;
  write(params?: $.Initializer<Hash_Write$Params>): Hash_Write$Results$Promise {
    const answer = this.client.call({
      method: Hash$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: Hash_Write$Params) => void
          : (target: Hash_Write$Params) => Hash_Write$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(Hash_Write$Results, answer);
    return new Hash_Write$Results$Promise(pipeline);
  }
  sum(): Hash_Sum$Results$Promise;
  sum(params: $.Init<Hash_Sum$Params>): Hash_Sum$Results$Promise;
  sum(paramsFunc: (params: Hash_Sum$Params) => void): Hash_Sum$Results$Promise;
  sum(params?: $.Initializer<Hash_Sum$Params>): Hash_Sum$Results$Promise {
    const answer = this.client.call({
      method: Hash$Client.methods[1],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: Hash_Sum$Params) => void
          : (target: Hash_Sum$Params) => Hash_Sum$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(Hash_Sum$Results, answer);
    return new Hash_Sum$Results$Promise(pipeline);
  }
}
$.Registry.register(Hash$Client.interfaceId, Hash$Client);
export interface Hash$Server$Target {
  write(params: Hash_Write$Params, results: Hash_Write$Results): $.MaybePromise<void | $.Init<Hash_Write$Results>>;
  sum(params: Hash_Sum$Params, results: Hash_Sum$Results): $.MaybePromise<void | $.Init<Hash_Sum$Results>>;
}
export class Hash$Server extends $.Server {
  readonly target: Hash$Server$Target;
  constructor(target: Hash$Server$Target) {
    super(target, [
      {
        ...Hash$Client.methods[0],
        impl: async (params: Hash_Write$Params, results: Hash_Write$Results) => {
          const value = await target.write(params, results);
          if (value !== undefined) {
            Hash_Write$Results._applyInit(results, value as $.Init<Hash_Write$Results>);
          }
        }
      },
      {
        ...Hash$Client.methods[1],
        impl: async (params: Hash_Sum$Params, results: Hash_Sum$Results) => {
          const value = await target.sum(params, results);
          if (value !== undefined) {
            Hash_Sum$Results._applyInit(results, value as $.Init<Hash_Sum$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): Hash$Client {
    return new Hash$Client(this);
  }
}
export class Hash extends $.Interface {
  static readonly Client = Hash$Client;
  static readonly Server = Hash$Server;
  static readonly _capnp = {
    displayName: "Hash",
    id: "e9620cda4245af9a",
    typeId: 0xe9620cda4245af9an,
    typeIdHex: "e9620cda4245af9a",
    size: new $.ObjectSize(0, 0),
    methods: Hash$Client.methods,
  };
  toString(): string { return "Hash_" + super.toString(); }
}
