// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
import { Baz } from "./import-bar.js";
export const _capnpFileId = 0xfc552bdafbb0b889n;
export class Foo extends $.Struct {
  static readonly BAZ_CONST = $.readRawPointer(new Uint8Array([16, 2, 64, 1, 0, 0]).buffer);
  static readonly _capnp = {
    displayName: "Foo",
    id: "f92e265d07c50136",
    typeId: 0xf92e265d07c50136n,
    typeIdHex: "f92e265d07c50136",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "baz", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "struct", typeId: 0xf2f28862b8e82db7n, typeIdHex: "f2f28862b8e82db7", displayName: "Baz" } }
    ] as const,
  };
  static _applyInit(target: Foo, value: $.Init<Foo>): void {
    const init = value as any;
    {
      const value = init["baz"];
      if (value !== undefined) {
        if (value instanceof Baz) {
          target.baz = value as Baz;
        }
        else {
          Baz._applyInit(target._initBaz(), value as $.Init<Baz>);
        }
      }
    }
  }
  _adoptBaz(value: $.Orphan<Baz>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownBaz(): $.Orphan<Baz> {
    return $.utils.disown(this.baz);
  }
  get baz(): Baz {
    return $.utils.getStruct(0, Baz, this);
  }
  _hasBaz(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initBaz(): Baz {
    return $.utils.initStructAt(0, Baz, this);
  }
  set baz(value: Baz) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "Foo_" + super.toString(); }
}
