// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
import { Foo } from "./import-foo.js";
export const _capnpFileId = 0x9cbc682922e84ff9n;
export class Baz extends $.Struct {
  static readonly FOO_CONST = $.readRawPointer(new Uint8Array([16, 2, 64, 1, 0, 0]).buffer);
  static readonly _capnp = {
    displayName: "Baz",
    id: "f2f28862b8e82db7",
    typeId: 0xf2f28862b8e82db7n,
    typeIdHex: "f2f28862b8e82db7",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "bar", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } }
    ] as const,
  };
  static _applyInit(target: Baz, value: $.Init<Baz>): void {
    const init = value as any;
    {
      const value = init["bar"];
      if (value !== undefined) {
        target.bar = value as any;
      }
    }
  }
  get bar(): string {
    return $.utils.getText(0, this);
  }
  set bar(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "Baz_" + super.toString(); }
}
