// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
import { SimpleInterface, SimpleInterface$Client } from "./simple-interface.js";
export const _capnpFileId = 0xeda41424bfc48a94n;
export class ReturnCapability_Get$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "get$Params",
    id: "b23eb0c5c51606ec",
    typeId: 0xb23eb0c5c51606ecn,
    typeIdHex: "b23eb0c5c51606ec",
    size: new $.ObjectSize(8, 0),
    fields: [
      { name: "index", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "int32" } }
    ] as const,
  };
  static _applyInit(target: ReturnCapability_Get$Params, value: $.Init<ReturnCapability_Get$Params>): void {
    const init = value;
    {
      const value = init["index"];
      if (value !== undefined) {
        target.index = value;
      }
    }
  }
  get index(): number {
    return $.utils.getInt32(0, this);
  }
  set index(value: number) {
    $.utils.setInt32(0, value, this);
  }
  toString(): string { return "ReturnCapability_Get$Params_" + super.toString(); }
}
export class ReturnCapability_Get$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "get$Results",
    id: "e578034f376aa46f",
    typeId: 0xe578034f376aa46fn,
    typeIdHex: "e578034f376aa46f",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "capability", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xdaf73e960b8928d6n, typeIdHex: "daf73e960b8928d6", displayName: "SimpleInterface" } }
    ] as const,
  };
  static _applyInit(target: ReturnCapability_Get$Results, value: $.Init<ReturnCapability_Get$Results>): void {
    const init = value;
    {
      const value = init["capability"];
      if (value !== undefined) {
        target.capability = value;
      }
    }
  }
  get capability(): SimpleInterface$Client {
    return new SimpleInterface$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  get capabilityOrNull(): SimpleInterface$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(0, this))?.getClient() ?? null;
    return client === null ? null : new SimpleInterface$Client(client);
  }
  set capabilityOrNull(value: SimpleInterface$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(0, this));
    }
    else {
      this.capability = value;
    }
  }
  set capability(value: SimpleInterface$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "ReturnCapability_Get$Results_" + super.toString(); }
}
export class ReturnCapability_Get$Results$Promise {
  pipeline: $.Pipeline<ReturnCapability_Get$Results, $.Struct, ReturnCapability_Get$Results>;
  constructor(pipeline: $.Pipeline<ReturnCapability_Get$Results, $.Struct, ReturnCapability_Get$Results>) {
    this.pipeline = pipeline;
  }
  getCapability(): SimpleInterface$Client {
    return new SimpleInterface$Client(this.pipeline.getPipeline(SimpleInterface, 0).client());
  }
  async promise(): Promise<ReturnCapability_Get$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = ReturnCapability_Get$Results, TResult2 = never>(onfulfilled?: ((value: ReturnCapability_Get$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<ReturnCapability_Get$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<ReturnCapability_Get$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class ReturnCapability$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xa3610792150745ffn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<ReturnCapability_Get$Params, ReturnCapability_Get$Results>
  ] = [
    {
      ParamsClass: ReturnCapability_Get$Params,
      ResultsClass: ReturnCapability_Get$Results,
      interfaceId: ReturnCapability$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/import-interface.capnp:ReturnCapability",
      methodName: "get",
      paramFields: ReturnCapability_Get$Params._capnp.fields,
      resultFields: ReturnCapability_Get$Results._capnp.fields
    }
  ];
  get(): ReturnCapability_Get$Results$Promise;
  get(params: $.Init<ReturnCapability_Get$Params>): ReturnCapability_Get$Results$Promise;
  get(paramsFunc: (params: ReturnCapability_Get$Params) => void): ReturnCapability_Get$Results$Promise;
  get(params?: $.Initializer<ReturnCapability_Get$Params>): ReturnCapability_Get$Results$Promise {
    const answer = this.client.call({
      method: ReturnCapability$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: ReturnCapability_Get$Params) => void
          : (target: ReturnCapability_Get$Params) => ReturnCapability_Get$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(ReturnCapability_Get$Results, answer);
    return new ReturnCapability_Get$Results$Promise(pipeline);
  }
}
$.Registry.register(ReturnCapability$Client.interfaceId, ReturnCapability$Client);
export interface ReturnCapability$Server$Target {
  get(params: ReturnCapability_Get$Params, results: ReturnCapability_Get$Results): $.MaybePromise<void | $.Init<ReturnCapability_Get$Results>>;
}
export class ReturnCapability$Server extends $.Server {
  readonly target: ReturnCapability$Server$Target;
  constructor(target: ReturnCapability$Server$Target) {
    super(target, [
      {
        ...ReturnCapability$Client.methods[0],
        impl: async (params: ReturnCapability_Get$Params, results: ReturnCapability_Get$Results) => {
          const value = await target.get(params, results);
          if (value !== undefined) {
            ReturnCapability_Get$Results._applyInit(results, value as $.Init<ReturnCapability_Get$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): ReturnCapability$Client {
    return new ReturnCapability$Client(this);
  }
}
export class ReturnCapability extends $.Interface {
  static readonly Client = ReturnCapability$Client;
  static readonly Server = ReturnCapability$Server;
  static readonly _capnp = {
    displayName: "ReturnCapability",
    id: "a3610792150745ff",
    typeId: 0xa3610792150745ffn,
    typeIdHex: "a3610792150745ff",
    size: new $.ObjectSize(0, 0),
    methods: ReturnCapability$Client.methods,
  };
  toString(): string { return "ReturnCapability_" + super.toString(); }
}
