// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
import { SimpleInterface, SimpleInterface$Client } from "./simple-interface.js";
export const _capnpFileId = 0xe9c293d743721d93n;
export class RpcLevel2Owner extends $.Struct {
  static readonly _capnp = {
    displayName: "RpcLevel2Owner",
    id: "91e080c1ac2ecb02",
    typeId: 0x91e080c1ac2ecb02n,
    typeIdHex: "91e080c1ac2ecb02",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "id", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } }
    ] as const,
  };
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "RpcLevel2Owner_" + super.toString(); }
}
export class RpcLevel2SturdyRef extends $.Struct {
  static readonly _capnp = {
    displayName: "RpcLevel2SturdyRef",
    id: "dc55e3c3188e2f10",
    typeId: 0xdc55e3c3188e2f10n,
    typeIdHex: "dc55e3c3188e2f10",
    size: new $.ObjectSize(0, 2),
    fields: [
      { name: "host", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "objectId", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "data" } }
    ] as const,
  };
  get host(): string {
    return $.utils.getText(0, this);
  }
  set host(value: string) {
    $.utils.setText(0, value, this);
  }
  _adoptObjectId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownObjectId(): $.Orphan<$.Data> {
    return $.utils.disown(this.objectId);
  }
  get objectId(): $.Data {
    return $.utils.getData(1, this);
  }
  _hasObjectId(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initObjectId(length: number): $.Data {
    return $.utils.initData(1, length, this);
  }
  set objectId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString(): string { return "RpcLevel2SturdyRef_" + super.toString(); }
}
export class RpcLevel2Restorer_Restore$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Params",
    id: "e1a41c4b120105f3",
    typeId: 0xe1a41c4b120105f3n,
    typeIdHex: "e1a41c4b120105f3",
    size: new $.ObjectSize(0, 2),
    fields: [
      { name: "sturdyRef", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "struct", typeId: 0xdc55e3c3188e2f10n, typeIdHex: "dc55e3c3188e2f10", displayName: "RpcLevel2SturdyRef" } },
      { name: "owner", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "struct", typeId: 0x91e080c1ac2ecb02n, typeIdHex: "91e080c1ac2ecb02", displayName: "RpcLevel2Owner" } }
    ] as const,
  };
  _adoptSturdyRef(value: $.Orphan<RpcLevel2SturdyRef>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownSturdyRef(): $.Orphan<RpcLevel2SturdyRef> {
    return $.utils.disown(this.sturdyRef);
  }
  get sturdyRef(): RpcLevel2SturdyRef {
    return $.utils.getStruct(0, RpcLevel2SturdyRef, this);
  }
  _hasSturdyRef(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initSturdyRef(): RpcLevel2SturdyRef {
    return $.utils.initStructAt(0, RpcLevel2SturdyRef, this);
  }
  set sturdyRef(value: RpcLevel2SturdyRef) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptOwner(value: $.Orphan<RpcLevel2Owner>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownOwner(): $.Orphan<RpcLevel2Owner> {
    return $.utils.disown(this.owner);
  }
  get owner(): RpcLevel2Owner {
    return $.utils.getStruct(1, RpcLevel2Owner, this);
  }
  _hasOwner(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initOwner(): RpcLevel2Owner {
    return $.utils.initStructAt(1, RpcLevel2Owner, this);
  }
  set owner(value: RpcLevel2Owner) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString(): string { return "RpcLevel2Restorer_Restore$Params_" + super.toString(); }
}
export class RpcLevel2Restorer_Restore$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Results",
    id: "e35054d5b9284804",
    typeId: 0xe35054d5b9284804n,
    typeIdHex: "e35054d5b9284804",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "capability", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xdaf73e960b8928d6n, typeIdHex: "daf73e960b8928d6", displayName: "SimpleInterface" } }
    ] as const,
  };
  get capability(): SimpleInterface$Client {
    return new SimpleInterface$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  set capability(value: SimpleInterface$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "RpcLevel2Restorer_Restore$Results_" + super.toString(); }
}
export class RpcLevel2Restorer_Restore$Results$Promise {
  pipeline: $.Pipeline<any, any, RpcLevel2Restorer_Restore$Results>;
  constructor(pipeline: $.Pipeline<any, any, RpcLevel2Restorer_Restore$Results>) {
    this.pipeline = pipeline;
  }
  getCapability(): SimpleInterface$Client {
    return new SimpleInterface$Client(this.pipeline.getPipeline(SimpleInterface, 0).client());
  }
  async promise(): Promise<RpcLevel2Restorer_Restore$Results> {
    return await this.pipeline.struct();
  }
}
export class RpcLevel2Restorer$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xe46163da857b06f9n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<RpcLevel2Restorer_Restore$Params, RpcLevel2Restorer_Restore$Results>
  ] = [
    {
      ParamsClass: RpcLevel2Restorer_Restore$Params,
      ResultsClass: RpcLevel2Restorer_Restore$Results,
      interfaceId: RpcLevel2Restorer$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/rpc-level2.capnp:RpcLevel2Restorer",
      methodName: "restore",
      paramFields: RpcLevel2Restorer_Restore$Params._capnp.fields,
      resultFields: RpcLevel2Restorer_Restore$Results._capnp.fields
    }
  ];
  restore(paramsFunc?: (params: RpcLevel2Restorer_Restore$Params) => void): RpcLevel2Restorer_Restore$Results$Promise {
    const answer = this.client.call({
      method: RpcLevel2Restorer$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(RpcLevel2Restorer_Restore$Results, answer);
    return new RpcLevel2Restorer_Restore$Results$Promise(pipeline);
  }
}
$.Registry.register(RpcLevel2Restorer$Client.interfaceId, RpcLevel2Restorer$Client);
export interface RpcLevel2Restorer$Server$Target {
  restore(params: RpcLevel2Restorer_Restore$Params, results: RpcLevel2Restorer_Restore$Results): Promise<void>;
}
export class RpcLevel2Restorer$Server extends $.Server {
  readonly target: RpcLevel2Restorer$Server$Target;
  constructor(target: RpcLevel2Restorer$Server$Target) {
    super(target, [
      {
        ...RpcLevel2Restorer$Client.methods[0],
        impl: target.restore
      }
    ]);
    this.target = target;
  }
  client(): RpcLevel2Restorer$Client {
    return new RpcLevel2Restorer$Client(this);
  }
}
export class RpcLevel2Restorer extends $.Interface {
  static readonly Client = RpcLevel2Restorer$Client;
  static readonly Server = RpcLevel2Restorer$Server;
  static readonly _capnp = {
    displayName: "RpcLevel2Restorer",
    id: "e46163da857b06f9",
    typeId: 0xe46163da857b06f9n,
    typeIdHex: "e46163da857b06f9",
    size: new $.ObjectSize(0, 0),
    methods: RpcLevel2Restorer$Client.methods,
  };
  toString(): string { return "RpcLevel2Restorer_" + super.toString(); }
}
export class RpcLevel2PersistenceService_Save$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "save$Params",
    id: "a7325bc8f051b6b9",
    typeId: 0xa7325bc8f051b6b9n,
    typeIdHex: "a7325bc8f051b6b9",
    size: new $.ObjectSize(0, 2),
    fields: [
      { name: "capability", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xdaf73e960b8928d6n, typeIdHex: "daf73e960b8928d6", displayName: "SimpleInterface" } },
      { name: "sealFor", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "struct", typeId: 0x91e080c1ac2ecb02n, typeIdHex: "91e080c1ac2ecb02", displayName: "RpcLevel2Owner" } }
    ] as const,
  };
  get capability(): SimpleInterface$Client {
    return new SimpleInterface$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  set capability(value: SimpleInterface$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  _adoptSealFor(value: $.Orphan<RpcLevel2Owner>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownSealFor(): $.Orphan<RpcLevel2Owner> {
    return $.utils.disown(this.sealFor);
  }
  get sealFor(): RpcLevel2Owner {
    return $.utils.getStruct(1, RpcLevel2Owner, this);
  }
  _hasSealFor(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initSealFor(): RpcLevel2Owner {
    return $.utils.initStructAt(1, RpcLevel2Owner, this);
  }
  set sealFor(value: RpcLevel2Owner) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString(): string { return "RpcLevel2PersistenceService_Save$Params_" + super.toString(); }
}
export class RpcLevel2PersistenceService_Save$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "save$Results",
    id: "cd80769c8501847f",
    typeId: 0xcd80769c8501847fn,
    typeIdHex: "cd80769c8501847f",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "sturdyRef", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "struct", typeId: 0xdc55e3c3188e2f10n, typeIdHex: "dc55e3c3188e2f10", displayName: "RpcLevel2SturdyRef" } }
    ] as const,
  };
  _adoptSturdyRef(value: $.Orphan<RpcLevel2SturdyRef>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownSturdyRef(): $.Orphan<RpcLevel2SturdyRef> {
    return $.utils.disown(this.sturdyRef);
  }
  get sturdyRef(): RpcLevel2SturdyRef {
    return $.utils.getStruct(0, RpcLevel2SturdyRef, this);
  }
  _hasSturdyRef(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initSturdyRef(): RpcLevel2SturdyRef {
    return $.utils.initStructAt(0, RpcLevel2SturdyRef, this);
  }
  set sturdyRef(value: RpcLevel2SturdyRef) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "RpcLevel2PersistenceService_Save$Results_" + super.toString(); }
}
export class RpcLevel2PersistenceService_Save$Results$Promise {
  pipeline: $.Pipeline<any, any, RpcLevel2PersistenceService_Save$Results>;
  constructor(pipeline: $.Pipeline<any, any, RpcLevel2PersistenceService_Save$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<RpcLevel2PersistenceService_Save$Results> {
    return await this.pipeline.struct();
  }
}
export class RpcLevel2PersistenceService_Restore$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Params",
    id: "e6e3144a8f69c47f",
    typeId: 0xe6e3144a8f69c47fn,
    typeIdHex: "e6e3144a8f69c47f",
    size: new $.ObjectSize(0, 2),
    fields: [
      { name: "sturdyRef", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "struct", typeId: 0xdc55e3c3188e2f10n, typeIdHex: "dc55e3c3188e2f10", displayName: "RpcLevel2SturdyRef" } },
      { name: "owner", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "struct", typeId: 0x91e080c1ac2ecb02n, typeIdHex: "91e080c1ac2ecb02", displayName: "RpcLevel2Owner" } }
    ] as const,
  };
  _adoptSturdyRef(value: $.Orphan<RpcLevel2SturdyRef>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownSturdyRef(): $.Orphan<RpcLevel2SturdyRef> {
    return $.utils.disown(this.sturdyRef);
  }
  get sturdyRef(): RpcLevel2SturdyRef {
    return $.utils.getStruct(0, RpcLevel2SturdyRef, this);
  }
  _hasSturdyRef(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initSturdyRef(): RpcLevel2SturdyRef {
    return $.utils.initStructAt(0, RpcLevel2SturdyRef, this);
  }
  set sturdyRef(value: RpcLevel2SturdyRef) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptOwner(value: $.Orphan<RpcLevel2Owner>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownOwner(): $.Orphan<RpcLevel2Owner> {
    return $.utils.disown(this.owner);
  }
  get owner(): RpcLevel2Owner {
    return $.utils.getStruct(1, RpcLevel2Owner, this);
  }
  _hasOwner(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initOwner(): RpcLevel2Owner {
    return $.utils.initStructAt(1, RpcLevel2Owner, this);
  }
  set owner(value: RpcLevel2Owner) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString(): string { return "RpcLevel2PersistenceService_Restore$Params_" + super.toString(); }
}
export class RpcLevel2PersistenceService_Restore$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Results",
    id: "bb86f71953078fac",
    typeId: 0xbb86f71953078facn,
    typeIdHex: "bb86f71953078fac",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "capability", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xdaf73e960b8928d6n, typeIdHex: "daf73e960b8928d6", displayName: "SimpleInterface" } }
    ] as const,
  };
  get capability(): SimpleInterface$Client {
    return new SimpleInterface$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  set capability(value: SimpleInterface$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "RpcLevel2PersistenceService_Restore$Results_" + super.toString(); }
}
export class RpcLevel2PersistenceService_Restore$Results$Promise {
  pipeline: $.Pipeline<any, any, RpcLevel2PersistenceService_Restore$Results>;
  constructor(pipeline: $.Pipeline<any, any, RpcLevel2PersistenceService_Restore$Results>) {
    this.pipeline = pipeline;
  }
  getCapability(): SimpleInterface$Client {
    return new SimpleInterface$Client(this.pipeline.getPipeline(SimpleInterface, 0).client());
  }
  async promise(): Promise<RpcLevel2PersistenceService_Restore$Results> {
    return await this.pipeline.struct();
  }
}
export class RpcLevel2PersistenceService$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xe76691615a9118ddn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<RpcLevel2PersistenceService_Save$Params, RpcLevel2PersistenceService_Save$Results>,
    $.Method<RpcLevel2PersistenceService_Restore$Params, RpcLevel2PersistenceService_Restore$Results>
  ] = [
    {
      ParamsClass: RpcLevel2PersistenceService_Save$Params,
      ResultsClass: RpcLevel2PersistenceService_Save$Results,
      interfaceId: RpcLevel2PersistenceService$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/rpc-level2.capnp:RpcLevel2PersistenceService",
      methodName: "save",
      paramFields: RpcLevel2PersistenceService_Save$Params._capnp.fields,
      resultFields: RpcLevel2PersistenceService_Save$Results._capnp.fields
    },
    {
      ParamsClass: RpcLevel2PersistenceService_Restore$Params,
      ResultsClass: RpcLevel2PersistenceService_Restore$Results,
      interfaceId: RpcLevel2PersistenceService$Client.interfaceId,
      methodId: 1,
      interfaceName: "test/fixtures/rpc-level2.capnp:RpcLevel2PersistenceService",
      methodName: "restore",
      paramFields: RpcLevel2PersistenceService_Restore$Params._capnp.fields,
      resultFields: RpcLevel2PersistenceService_Restore$Results._capnp.fields
    }
  ];
  save(paramsFunc?: (params: RpcLevel2PersistenceService_Save$Params) => void): RpcLevel2PersistenceService_Save$Results$Promise {
    const answer = this.client.call({
      method: RpcLevel2PersistenceService$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(RpcLevel2PersistenceService_Save$Results, answer);
    return new RpcLevel2PersistenceService_Save$Results$Promise(pipeline);
  }
  restore(paramsFunc?: (params: RpcLevel2PersistenceService_Restore$Params) => void): RpcLevel2PersistenceService_Restore$Results$Promise {
    const answer = this.client.call({
      method: RpcLevel2PersistenceService$Client.methods[1],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(RpcLevel2PersistenceService_Restore$Results, answer);
    return new RpcLevel2PersistenceService_Restore$Results$Promise(pipeline);
  }
}
$.Registry.register(RpcLevel2PersistenceService$Client.interfaceId, RpcLevel2PersistenceService$Client);
export interface RpcLevel2PersistenceService$Server$Target {
  save(params: RpcLevel2PersistenceService_Save$Params, results: RpcLevel2PersistenceService_Save$Results): Promise<void>;
  restore(params: RpcLevel2PersistenceService_Restore$Params, results: RpcLevel2PersistenceService_Restore$Results): Promise<void>;
}
export class RpcLevel2PersistenceService$Server extends $.Server {
  readonly target: RpcLevel2PersistenceService$Server$Target;
  constructor(target: RpcLevel2PersistenceService$Server$Target) {
    super(target, [
      {
        ...RpcLevel2PersistenceService$Client.methods[0],
        impl: target.save
      },
      {
        ...RpcLevel2PersistenceService$Client.methods[1],
        impl: target.restore
      }
    ]);
    this.target = target;
  }
  client(): RpcLevel2PersistenceService$Client {
    return new RpcLevel2PersistenceService$Client(this);
  }
}
export class RpcLevel2PersistenceService extends $.Interface {
  static readonly Client = RpcLevel2PersistenceService$Client;
  static readonly Server = RpcLevel2PersistenceService$Server;
  static readonly _capnp = {
    displayName: "RpcLevel2PersistenceService",
    id: "e76691615a9118dd",
    typeId: 0xe76691615a9118ddn,
    typeIdHex: "e76691615a9118dd",
    size: new $.ObjectSize(0, 0),
    methods: RpcLevel2PersistenceService$Client.methods,
  };
  toString(): string { return "RpcLevel2PersistenceService_" + super.toString(); }
}
