// This file has been automatically generated by capnp-es.
import * as $ from "./capnp-runtime-shim.js";
export const _capnpFileId = 0xdb9167bc4be31a1en;
export class AppPersistent_Save$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "save$Params",
    id: "bb124a76f24faf90",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "AppPersistent_Save$Params_" + super.toString(); }
}
export class AppPersistent_Save$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "save$Results",
    id: "c76e8d6ea6ecaca9",
    size: new $.ObjectSize(0, 1),
  };
  _adoptObjectId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownObjectId(): $.Orphan<$.Data> {
    return $.utils.disown(this.objectId);
  }
  get objectId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasObjectId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initObjectId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set objectId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "AppPersistent_Save$Results_" + super.toString(); }
}
export class AppPersistent_Save$Results$Promise {
  pipeline: $.Pipeline<any, any, AppPersistent_Save$Results>;
  constructor(pipeline: $.Pipeline<any, any, AppPersistent_Save$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<AppPersistent_Save$Results> {
    return await this.pipeline.struct();
  }
}
export class AppPersistent$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0x94d3ee75eb8a7016n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<AppPersistent_Save$Params, AppPersistent_Save$Results>
  ] = [
    {
      ParamsClass: AppPersistent_Save$Params,
      ResultsClass: AppPersistent_Save$Results,
      interfaceId: AppPersistent$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppPersistent",
      methodName: "save"
    }
  ];
  save(paramsFunc?: (params: AppPersistent_Save$Params) => void): AppPersistent_Save$Results$Promise {
    const answer = this.client.call({
      method: AppPersistent$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(AppPersistent_Save$Results, answer);
    return new AppPersistent_Save$Results$Promise(pipeline);
  }
}
$.Registry.register(AppPersistent$Client.interfaceId, AppPersistent$Client);
export interface AppPersistent$Server$Target {
  save(params: AppPersistent_Save$Params, results: AppPersistent_Save$Results): Promise<void>;
}
export class AppPersistent$Server extends $.Server {
  readonly target: AppPersistent$Server$Target;
  constructor(target: AppPersistent$Server$Target) {
    super(target, [
      {
        ...AppPersistent$Client.methods[0],
        impl: target.save
      }
    ]);
    this.target = target;
  }
  client(): AppPersistent$Client {
    return new AppPersistent$Client(this);
  }
}
export class AppPersistent extends $.Interface {
  static readonly Client = AppPersistent$Client;
  static readonly Server = AppPersistent$Server;
  static readonly _capnp = {
    displayName: "AppPersistent",
    id: "94d3ee75eb8a7016",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "AppPersistent_" + super.toString(); }
}
export class Node_Stat$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "stat$Params",
    id: "bfb4c532efe76573",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "Node_Stat$Params_" + super.toString(); }
}
export class Node_Stat$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "stat$Results",
    id: "ff853c77c4117b43",
    size: new $.ObjectSize(8, 0),
  };
  get isDir(): boolean {
    return $.utils.getBit(0, this);
  }
  set isDir(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  toString(): string { return "Node_Stat$Results_" + super.toString(); }
}
export class Node_Stat$Results$Promise {
  pipeline: $.Pipeline<any, any, Node_Stat$Results>;
  constructor(pipeline: $.Pipeline<any, any, Node_Stat$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<Node_Stat$Results> {
    return await this.pipeline.struct();
  }
}
export class Node$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xd17a48af23601b7cn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<Node_Stat$Params, Node_Stat$Results>
  ] = [
    {
      ParamsClass: Node_Stat$Params,
      ResultsClass: Node_Stat$Results,
      interfaceId: Node$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:Node",
      methodName: "stat"
    }
  ];
  stat(paramsFunc?: (params: Node_Stat$Params) => void): Node_Stat$Results$Promise {
    const answer = this.client.call({
      method: Node$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(Node_Stat$Results, answer);
    return new Node_Stat$Results$Promise(pipeline);
  }
}
$.Registry.register(Node$Client.interfaceId, Node$Client);
export interface Node$Server$Target {
  stat(params: Node_Stat$Params, results: Node_Stat$Results): Promise<void>;
}
export class Node$Server extends $.Server {
  readonly target: Node$Server$Target;
  constructor(target: Node$Server$Target) {
    super(target, [
      {
        ...Node$Client.methods[0],
        impl: target.stat
      }
    ]);
    this.target = target;
  }
  client(): Node$Client {
    return new Node$Client(this);
  }
}
export class Node extends $.Interface {
  static readonly Client = Node$Client;
  static readonly Server = Node$Server;
  static readonly _capnp = {
    displayName: "Node",
    id: "d17a48af23601b7c",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "Node_" + super.toString(); }
}
export class AppHooks_GetViewInfo$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "getViewInfo$Params",
    id: "868b5b92c9347347",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "AppHooks_GetViewInfo$Params_" + super.toString(); }
}
export class AppHooks_GetViewInfo$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "getViewInfo$Results",
    id: "a80a104d8a8a616f",
    size: new $.ObjectSize(8, 0),
  };
  get supportsNode(): boolean {
    return $.utils.getBit(0, this);
  }
  set supportsNode(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  toString(): string { return "AppHooks_GetViewInfo$Results_" + super.toString(); }
}
export class AppHooks_GetViewInfo$Results$Promise {
  pipeline: $.Pipeline<any, any, AppHooks_GetViewInfo$Results>;
  constructor(pipeline: $.Pipeline<any, any, AppHooks_GetViewInfo$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<AppHooks_GetViewInfo$Results> {
    return await this.pipeline.struct();
  }
}
export class AppHooks_Restore$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Params",
    id: "ea0b23950ff318d6",
    size: new $.ObjectSize(0, 1),
  };
  _adoptObjectId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownObjectId(): $.Orphan<$.Data> {
    return $.utils.disown(this.objectId);
  }
  get objectId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasObjectId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initObjectId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set objectId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "AppHooks_Restore$Params_" + super.toString(); }
}
export class AppHooks_Restore$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Results",
    id: "a660c3ced1a268a5",
    size: new $.ObjectSize(0, 1),
  };
  get cap(): Node$Client {
    return new Node$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  set cap(value: Node$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "AppHooks_Restore$Results_" + super.toString(); }
}
export class AppHooks_Restore$Results$Promise {
  pipeline: $.Pipeline<any, any, AppHooks_Restore$Results>;
  constructor(pipeline: $.Pipeline<any, any, AppHooks_Restore$Results>) {
    this.pipeline = pipeline;
  }
  getCap(): Node$Client {
    return new Node$Client(this.pipeline.getPipeline(Node, 0).client());
  }
  async promise(): Promise<AppHooks_Restore$Results> {
    return await this.pipeline.struct();
  }
}
export class AppHooks_Drop$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "drop$Params",
    id: "d3abb96331d2e243",
    size: new $.ObjectSize(0, 1),
  };
  _adoptObjectId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownObjectId(): $.Orphan<$.Data> {
    return $.utils.disown(this.objectId);
  }
  get objectId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasObjectId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initObjectId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set objectId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "AppHooks_Drop$Params_" + super.toString(); }
}
export class AppHooks_Drop$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "drop$Results",
    id: "b34e9b18133a8ea2",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "AppHooks_Drop$Results_" + super.toString(); }
}
export class AppHooks_Drop$Results$Promise {
  pipeline: $.Pipeline<any, any, AppHooks_Drop$Results>;
  constructor(pipeline: $.Pipeline<any, any, AppHooks_Drop$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<AppHooks_Drop$Results> {
    return await this.pipeline.struct();
  }
}
export class AppHooks$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xa3da9e3e6f3e32cbn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<AppHooks_GetViewInfo$Params, AppHooks_GetViewInfo$Results>,
    $.Method<AppHooks_Restore$Params, AppHooks_Restore$Results>,
    $.Method<AppHooks_Drop$Params, AppHooks_Drop$Results>
  ] = [
    {
      ParamsClass: AppHooks_GetViewInfo$Params,
      ResultsClass: AppHooks_GetViewInfo$Results,
      interfaceId: AppHooks$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppHooks",
      methodName: "getViewInfo"
    },
    {
      ParamsClass: AppHooks_Restore$Params,
      ResultsClass: AppHooks_Restore$Results,
      interfaceId: AppHooks$Client.interfaceId,
      methodId: 1,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppHooks",
      methodName: "restore"
    },
    {
      ParamsClass: AppHooks_Drop$Params,
      ResultsClass: AppHooks_Drop$Results,
      interfaceId: AppHooks$Client.interfaceId,
      methodId: 2,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppHooks",
      methodName: "drop"
    }
  ];
  getViewInfo(paramsFunc?: (params: AppHooks_GetViewInfo$Params) => void): AppHooks_GetViewInfo$Results$Promise {
    const answer = this.client.call({
      method: AppHooks$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(AppHooks_GetViewInfo$Results, answer);
    return new AppHooks_GetViewInfo$Results$Promise(pipeline);
  }
  restore(paramsFunc?: (params: AppHooks_Restore$Params) => void): AppHooks_Restore$Results$Promise {
    const answer = this.client.call({
      method: AppHooks$Client.methods[1],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(AppHooks_Restore$Results, answer);
    return new AppHooks_Restore$Results$Promise(pipeline);
  }
  drop(paramsFunc?: (params: AppHooks_Drop$Params) => void): AppHooks_Drop$Results$Promise {
    const answer = this.client.call({
      method: AppHooks$Client.methods[2],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(AppHooks_Drop$Results, answer);
    return new AppHooks_Drop$Results$Promise(pipeline);
  }
}
$.Registry.register(AppHooks$Client.interfaceId, AppHooks$Client);
export interface AppHooks$Server$Target {
  getViewInfo(params: AppHooks_GetViewInfo$Params, results: AppHooks_GetViewInfo$Results): Promise<void>;
  restore(params: AppHooks_Restore$Params, results: AppHooks_Restore$Results): Promise<void>;
  drop(params: AppHooks_Drop$Params, results: AppHooks_Drop$Results): Promise<void>;
}
export class AppHooks$Server extends $.Server {
  readonly target: AppHooks$Server$Target;
  constructor(target: AppHooks$Server$Target) {
    super(target, [
      {
        ...AppHooks$Client.methods[0],
        impl: target.getViewInfo
      },
      {
        ...AppHooks$Client.methods[1],
        impl: target.restore
      },
      {
        ...AppHooks$Client.methods[2],
        impl: target.drop
      }
    ]);
    this.target = target;
  }
  client(): AppHooks$Client {
    return new AppHooks$Client(this);
  }
}
export class AppHooks extends $.Interface {
  static readonly Client = AppHooks$Client;
  static readonly Server = AppHooks$Server;
  static readonly _capnp = {
    displayName: "AppHooks",
    id: "a3da9e3e6f3e32cb",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "AppHooks_" + super.toString(); }
}
export class SessionContext_FulfillRequest$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "fulfillRequest$Params",
    id: "dad774a13a5ea885",
    size: new $.ObjectSize(0, 1),
  };
  get cap(): Node$Client {
    return new Node$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  set cap(value: Node$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "SessionContext_FulfillRequest$Params_" + super.toString(); }
}
export class SessionContext_FulfillRequest$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "fulfillRequest$Results",
    id: "fedf2733a226251b",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "SessionContext_FulfillRequest$Results_" + super.toString(); }
}
export class SessionContext_FulfillRequest$Results$Promise {
  pipeline: $.Pipeline<any, any, SessionContext_FulfillRequest$Results>;
  constructor(pipeline: $.Pipeline<any, any, SessionContext_FulfillRequest$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<SessionContext_FulfillRequest$Results> {
    return await this.pipeline.struct();
  }
}
export class SessionContext_ClaimRequest$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "claimRequest$Params",
    id: "d77f7210aff2abc8",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "SessionContext_ClaimRequest$Params_" + super.toString(); }
}
export class SessionContext_ClaimRequest$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "claimRequest$Results",
    id: "cc12bb836653bd0a",
    size: new $.ObjectSize(0, 1),
  };
  get cap(): Node$Client {
    return new Node$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  set cap(value: Node$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "SessionContext_ClaimRequest$Results_" + super.toString(); }
}
export class SessionContext_ClaimRequest$Results$Promise {
  pipeline: $.Pipeline<any, any, SessionContext_ClaimRequest$Results>;
  constructor(pipeline: $.Pipeline<any, any, SessionContext_ClaimRequest$Results>) {
    this.pipeline = pipeline;
  }
  getCap(): Node$Client {
    return new Node$Client(this.pipeline.getPipeline(Node, 0).client());
  }
  async promise(): Promise<SessionContext_ClaimRequest$Results> {
    return await this.pipeline.struct();
  }
}
export class SessionContext$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xb82638dbadc07fe5n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<SessionContext_FulfillRequest$Params, SessionContext_FulfillRequest$Results>,
    $.Method<SessionContext_ClaimRequest$Params, SessionContext_ClaimRequest$Results>
  ] = [
    {
      ParamsClass: SessionContext_FulfillRequest$Params,
      ResultsClass: SessionContext_FulfillRequest$Results,
      interfaceId: SessionContext$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:SessionContext",
      methodName: "fulfillRequest"
    },
    {
      ParamsClass: SessionContext_ClaimRequest$Params,
      ResultsClass: SessionContext_ClaimRequest$Results,
      interfaceId: SessionContext$Client.interfaceId,
      methodId: 1,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:SessionContext",
      methodName: "claimRequest"
    }
  ];
  fulfillRequest(paramsFunc?: (params: SessionContext_FulfillRequest$Params) => void): SessionContext_FulfillRequest$Results$Promise {
    const answer = this.client.call({
      method: SessionContext$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(SessionContext_FulfillRequest$Results, answer);
    return new SessionContext_FulfillRequest$Results$Promise(pipeline);
  }
  claimRequest(paramsFunc?: (params: SessionContext_ClaimRequest$Params) => void): SessionContext_ClaimRequest$Results$Promise {
    const answer = this.client.call({
      method: SessionContext$Client.methods[1],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(SessionContext_ClaimRequest$Results, answer);
    return new SessionContext_ClaimRequest$Results$Promise(pipeline);
  }
}
$.Registry.register(SessionContext$Client.interfaceId, SessionContext$Client);
export interface SessionContext$Server$Target {
  fulfillRequest(params: SessionContext_FulfillRequest$Params, results: SessionContext_FulfillRequest$Results): Promise<void>;
  claimRequest(params: SessionContext_ClaimRequest$Params, results: SessionContext_ClaimRequest$Results): Promise<void>;
}
export class SessionContext$Server extends $.Server {
  readonly target: SessionContext$Server$Target;
  constructor(target: SessionContext$Server$Target) {
    super(target, [
      {
        ...SessionContext$Client.methods[0],
        impl: target.fulfillRequest
      },
      {
        ...SessionContext$Client.methods[1],
        impl: target.claimRequest
      }
    ]);
    this.target = target;
  }
  client(): SessionContext$Client {
    return new SessionContext$Client(this);
  }
}
export class SessionContext extends $.Interface {
  static readonly Client = SessionContext$Client;
  static readonly Server = SessionContext$Server;
  static readonly _capnp = {
    displayName: "SessionContext",
    id: "b82638dbadc07fe5",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "SessionContext_" + super.toString(); }
}
export class SandstormBridge_GetSessionContext$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "getSessionContext$Params",
    id: "d6185b98019425b7",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "SandstormBridge_GetSessionContext$Params_" + super.toString(); }
}
export class SandstormBridge_GetSessionContext$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "getSessionContext$Results",
    id: "87c8ebb952dee654",
    size: new $.ObjectSize(0, 1),
  };
  get context(): SessionContext$Client {
    return new SessionContext$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  set context(value: SessionContext$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "SandstormBridge_GetSessionContext$Results_" + super.toString(); }
}
export class SandstormBridge_GetSessionContext$Results$Promise {
  pipeline: $.Pipeline<any, any, SandstormBridge_GetSessionContext$Results>;
  constructor(pipeline: $.Pipeline<any, any, SandstormBridge_GetSessionContext$Results>) {
    this.pipeline = pipeline;
  }
  getContext(): SessionContext$Client {
    return new SessionContext$Client(this.pipeline.getPipeline(SessionContext, 0).client());
  }
  async promise(): Promise<SandstormBridge_GetSessionContext$Results> {
    return await this.pipeline.struct();
  }
}
export class SandstormBridge$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0x924ba13008df5c6fn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<SandstormBridge_GetSessionContext$Params, SandstormBridge_GetSessionContext$Results>
  ] = [
    {
      ParamsClass: SandstormBridge_GetSessionContext$Params,
      ResultsClass: SandstormBridge_GetSessionContext$Results,
      interfaceId: SandstormBridge$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:SandstormBridge",
      methodName: "getSessionContext"
    }
  ];
  getSessionContext(paramsFunc?: (params: SandstormBridge_GetSessionContext$Params) => void): SandstormBridge_GetSessionContext$Results$Promise {
    const answer = this.client.call({
      method: SandstormBridge$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(SandstormBridge_GetSessionContext$Results, answer);
    return new SandstormBridge_GetSessionContext$Results$Promise(pipeline);
  }
}
$.Registry.register(SandstormBridge$Client.interfaceId, SandstormBridge$Client);
export interface SandstormBridge$Server$Target {
  getSessionContext(params: SandstormBridge_GetSessionContext$Params, results: SandstormBridge_GetSessionContext$Results): Promise<void>;
}
export class SandstormBridge$Server extends $.Server {
  readonly target: SandstormBridge$Server$Target;
  constructor(target: SandstormBridge$Server$Target) {
    super(target, [
      {
        ...SandstormBridge$Client.methods[0],
        impl: target.getSessionContext
      }
    ]);
    this.target = target;
  }
  client(): SandstormBridge$Client {
    return new SandstormBridge$Client(this);
  }
}
export class SandstormBridge extends $.Interface {
  static readonly Client = SandstormBridge$Client;
  static readonly Server = SandstormBridge$Server;
  static readonly _capnp = {
    displayName: "SandstormBridge",
    id: "924ba13008df5c6f",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "SandstormBridge_" + super.toString(); }
}
