// This file has been automatically generated by capnp-es.
import * as $ from "./capnp-runtime-shim.js";
export const _capnpFileId = 0xdb9167bc4be31a1en;
export class AppPersistent_Save$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "save$Params",
    id: "bb124a76f24faf90",
    typeId: 0xbb124a76f24faf90n,
    typeIdHex: "bb124a76f24faf90",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: AppPersistent_Save$Params, value: $.Init<AppPersistent_Save$Params>): void {
    const init = value;
  }
  toString(): string { return "AppPersistent_Save$Params_" + super.toString(); }
}
export class AppPersistent_Save$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "save$Results",
    id: "c76e8d6ea6ecaca9",
    typeId: 0xc76e8d6ea6ecaca9n,
    typeIdHex: "c76e8d6ea6ecaca9",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "objectId", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "data" } }
    ] as const,
  };
  static _applyInit(target: AppPersistent_Save$Results, value: $.Init<AppPersistent_Save$Results>): void {
    const init = value;
    {
      const value = init["objectId"];
      if (value !== undefined) {
        if (value instanceof $.Data) {
          target.objectId = value;
        }
        else {
          const bytes = $.dataBytes(value);
          target._initObjectId(bytes.byteLength).copyBuffer(bytes);
        }
      }
    }
  }
  _adoptObjectId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownObjectId(): $.Orphan<$.Data> {
    return $.utils.disown(this.objectId);
  }
  get objectId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasObjectId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initObjectId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set objectId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "AppPersistent_Save$Results_" + super.toString(); }
}
export class AppPersistent_Save$Results$Promise {
  pipeline: $.Pipeline<AppPersistent_Save$Results, $.Struct, AppPersistent_Save$Results>;
  constructor(pipeline: $.Pipeline<AppPersistent_Save$Results, $.Struct, AppPersistent_Save$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<AppPersistent_Save$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = AppPersistent_Save$Results, TResult2 = never>(onfulfilled?: ((value: AppPersistent_Save$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<AppPersistent_Save$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<AppPersistent_Save$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class AppPersistent$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0x94d3ee75eb8a7016n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<AppPersistent_Save$Params, AppPersistent_Save$Results>
  ] = [
    {
      ParamsClass: AppPersistent_Save$Params,
      ResultsClass: AppPersistent_Save$Results,
      interfaceId: AppPersistent$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppPersistent",
      methodName: "save",
      paramFields: AppPersistent_Save$Params._capnp.fields,
      resultFields: AppPersistent_Save$Results._capnp.fields
    }
  ];
  save(): AppPersistent_Save$Results$Promise;
  save(params: $.Init<AppPersistent_Save$Params>): AppPersistent_Save$Results$Promise;
  save(paramsFunc: (params: AppPersistent_Save$Params) => void): AppPersistent_Save$Results$Promise;
  save(params?: $.Initializer<AppPersistent_Save$Params>): AppPersistent_Save$Results$Promise {
    const answer = this.client.call({
      method: AppPersistent$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: AppPersistent_Save$Params) => void
          : (target: AppPersistent_Save$Params) => AppPersistent_Save$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(AppPersistent_Save$Results, answer);
    return new AppPersistent_Save$Results$Promise(pipeline);
  }
}
$.Registry.register(AppPersistent$Client.interfaceId, AppPersistent$Client);
export interface AppPersistent$Server$Target {
  save(params: AppPersistent_Save$Params, results: AppPersistent_Save$Results): $.MaybePromise<void | $.Init<AppPersistent_Save$Results>>;
}
export class AppPersistent$Server extends $.Server {
  readonly target: AppPersistent$Server$Target;
  constructor(target: AppPersistent$Server$Target) {
    super(target, [
      {
        ...AppPersistent$Client.methods[0],
        impl: async (params: AppPersistent_Save$Params, results: AppPersistent_Save$Results) => {
          const value = await target.save(params, results);
          if (value !== undefined) {
            AppPersistent_Save$Results._applyInit(results, value as $.Init<AppPersistent_Save$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): AppPersistent$Client {
    return new AppPersistent$Client(this);
  }
}
export class AppPersistent extends $.Interface {
  static readonly Client = AppPersistent$Client;
  static readonly Server = AppPersistent$Server;
  static readonly _capnp = {
    displayName: "AppPersistent",
    id: "94d3ee75eb8a7016",
    typeId: 0x94d3ee75eb8a7016n,
    typeIdHex: "94d3ee75eb8a7016",
    size: new $.ObjectSize(0, 0),
    methods: AppPersistent$Client.methods,
  };
  toString(): string { return "AppPersistent_" + super.toString(); }
}
export class Node_Stat$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "stat$Params",
    id: "bfb4c532efe76573",
    typeId: 0xbfb4c532efe76573n,
    typeIdHex: "bfb4c532efe76573",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: Node_Stat$Params, value: $.Init<Node_Stat$Params>): void {
    const init = value;
  }
  toString(): string { return "Node_Stat$Params_" + super.toString(); }
}
export class Node_Stat$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "stat$Results",
    id: "ff853c77c4117b43",
    typeId: 0xff853c77c4117b43n,
    typeIdHex: "ff853c77c4117b43",
    size: new $.ObjectSize(8, 0),
    fields: [
      { name: "isDir", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "bool" } }
    ] as const,
  };
  static _applyInit(target: Node_Stat$Results, value: $.Init<Node_Stat$Results>): void {
    const init = value;
    {
      const value = init["isDir"];
      if (value !== undefined) {
        target.isDir = value;
      }
    }
  }
  get isDir(): boolean {
    return $.utils.getBit(0, this);
  }
  set isDir(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  toString(): string { return "Node_Stat$Results_" + super.toString(); }
}
export class Node_Stat$Results$Promise {
  pipeline: $.Pipeline<Node_Stat$Results, $.Struct, Node_Stat$Results>;
  constructor(pipeline: $.Pipeline<Node_Stat$Results, $.Struct, Node_Stat$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<Node_Stat$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = Node_Stat$Results, TResult2 = never>(onfulfilled?: ((value: Node_Stat$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<Node_Stat$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<Node_Stat$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class Node$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xd17a48af23601b7cn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly ownMethods: [
    $.Method<Node_Stat$Params, Node_Stat$Results>
  ] = [
    {
      ParamsClass: Node_Stat$Params,
      ResultsClass: Node_Stat$Results,
      interfaceId: Node$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:Node",
      methodName: "stat",
      paramFields: Node_Stat$Params._capnp.fields,
      resultFields: Node_Stat$Results._capnp.fields
    }
  ];
  static readonly methods: $.Method<$.Struct, $.Struct>[] = [
    ...AppPersistent$Client.methods,
    ...Node$Client.ownMethods
  ];
  save(...args: Parameters<AppPersistent$Client["save"]>): ReturnType<AppPersistent$Client["save"]> {
    return AppPersistent$Client.prototype.save.apply(this, args);
  }
  stat(): Node_Stat$Results$Promise;
  stat(params: $.Init<Node_Stat$Params>): Node_Stat$Results$Promise;
  stat(paramsFunc: (params: Node_Stat$Params) => void): Node_Stat$Results$Promise;
  stat(params?: $.Initializer<Node_Stat$Params>): Node_Stat$Results$Promise {
    const answer = this.client.call({
      method: Node$Client.ownMethods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: Node_Stat$Params) => void
          : (target: Node_Stat$Params) => Node_Stat$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(Node_Stat$Results, answer);
    return new Node_Stat$Results$Promise(pipeline);
  }
}
$.Registry.register(Node$Client.interfaceId, Node$Client);
export interface Node$Server$Target extends AppPersistent$Server$Target {
  stat(params: Node_Stat$Params, results: Node_Stat$Results): $.MaybePromise<void | $.Init<Node_Stat$Results>>;
}
export class Node$Server extends $.Server {
  readonly target: Node$Server$Target;
  constructor(target: Node$Server$Target) {
    super(target, [
      ...(AppPersistent$Client.methods as $.Method<$.Struct, $.Struct>[]).map((method) => ({
        ...method,
        impl: async (params: $.Struct, results: $.Struct) => {
          const targetMethod = target[method.methodName as keyof Node$Server$Target] as unknown as (params: $.Struct, results: $.Struct) => $.MaybePromise<void | $.Init<$.Struct>>;
          const value = await targetMethod.call(target, params, results);
          if (value !== undefined) {
            $.applyInit(results, value);
          }
        }
      })),
      {
        ...Node$Client.ownMethods[0],
        impl: async (params: Node_Stat$Params, results: Node_Stat$Results) => {
          const value = await target.stat(params, results);
          if (value !== undefined) {
            Node_Stat$Results._applyInit(results, value as $.Init<Node_Stat$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): Node$Client {
    return new Node$Client(this);
  }
}
export class Node extends $.Interface {
  static readonly Client = Node$Client;
  static readonly Server = Node$Server;
  static readonly _capnp = {
    displayName: "Node",
    id: "d17a48af23601b7c",
    typeId: 0xd17a48af23601b7cn,
    typeIdHex: "d17a48af23601b7c",
    size: new $.ObjectSize(0, 0),
    methods: Node$Client.methods,
  };
  toString(): string { return "Node_" + super.toString(); }
}
export class AppHooks_GetViewInfo$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "getViewInfo$Params",
    id: "868b5b92c9347347",
    typeId: 0x868b5b92c9347347n,
    typeIdHex: "868b5b92c9347347",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: AppHooks_GetViewInfo$Params, value: $.Init<AppHooks_GetViewInfo$Params>): void {
    const init = value;
  }
  toString(): string { return "AppHooks_GetViewInfo$Params_" + super.toString(); }
}
export class AppHooks_GetViewInfo$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "getViewInfo$Results",
    id: "a80a104d8a8a616f",
    typeId: 0xa80a104d8a8a616fn,
    typeIdHex: "a80a104d8a8a616f",
    size: new $.ObjectSize(8, 0),
    fields: [
      { name: "supportsNode", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "bool" } }
    ] as const,
  };
  static _applyInit(target: AppHooks_GetViewInfo$Results, value: $.Init<AppHooks_GetViewInfo$Results>): void {
    const init = value;
    {
      const value = init["supportsNode"];
      if (value !== undefined) {
        target.supportsNode = value;
      }
    }
  }
  get supportsNode(): boolean {
    return $.utils.getBit(0, this);
  }
  set supportsNode(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  toString(): string { return "AppHooks_GetViewInfo$Results_" + super.toString(); }
}
export class AppHooks_GetViewInfo$Results$Promise {
  pipeline: $.Pipeline<AppHooks_GetViewInfo$Results, $.Struct, AppHooks_GetViewInfo$Results>;
  constructor(pipeline: $.Pipeline<AppHooks_GetViewInfo$Results, $.Struct, AppHooks_GetViewInfo$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<AppHooks_GetViewInfo$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = AppHooks_GetViewInfo$Results, TResult2 = never>(onfulfilled?: ((value: AppHooks_GetViewInfo$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<AppHooks_GetViewInfo$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<AppHooks_GetViewInfo$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class AppHooks_Restore$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Params",
    id: "ea0b23950ff318d6",
    typeId: 0xea0b23950ff318d6n,
    typeIdHex: "ea0b23950ff318d6",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "objectId", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "data" } }
    ] as const,
  };
  static _applyInit(target: AppHooks_Restore$Params, value: $.Init<AppHooks_Restore$Params>): void {
    const init = value;
    {
      const value = init["objectId"];
      if (value !== undefined) {
        if (value instanceof $.Data) {
          target.objectId = value;
        }
        else {
          const bytes = $.dataBytes(value);
          target._initObjectId(bytes.byteLength).copyBuffer(bytes);
        }
      }
    }
  }
  _adoptObjectId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownObjectId(): $.Orphan<$.Data> {
    return $.utils.disown(this.objectId);
  }
  get objectId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasObjectId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initObjectId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set objectId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "AppHooks_Restore$Params_" + super.toString(); }
}
export class AppHooks_Restore$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "restore$Results",
    id: "a660c3ced1a268a5",
    typeId: 0xa660c3ced1a268a5n,
    typeIdHex: "a660c3ced1a268a5",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "cap", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xd17a48af23601b7cn, typeIdHex: "d17a48af23601b7c", displayName: "Node" } }
    ] as const,
  };
  static _applyInit(target: AppHooks_Restore$Results, value: $.Init<AppHooks_Restore$Results>): void {
    const init = value;
    {
      const value = init["cap"];
      if (value !== undefined) {
        target.cap = value;
      }
    }
  }
  get cap(): Node$Client {
    return new Node$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  get capOrNull(): Node$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(0, this))?.getClient() ?? null;
    return client === null ? null : new Node$Client(client);
  }
  set capOrNull(value: Node$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(0, this));
    }
    else {
      this.cap = value;
    }
  }
  set cap(value: Node$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "AppHooks_Restore$Results_" + super.toString(); }
}
export class AppHooks_Restore$Results$Promise {
  pipeline: $.Pipeline<AppHooks_Restore$Results, $.Struct, AppHooks_Restore$Results>;
  constructor(pipeline: $.Pipeline<AppHooks_Restore$Results, $.Struct, AppHooks_Restore$Results>) {
    this.pipeline = pipeline;
  }
  getCap(): Node$Client {
    return new Node$Client(this.pipeline.getPipeline(Node, 0).client());
  }
  async promise(): Promise<AppHooks_Restore$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = AppHooks_Restore$Results, TResult2 = never>(onfulfilled?: ((value: AppHooks_Restore$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<AppHooks_Restore$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<AppHooks_Restore$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class AppHooks_Drop$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "drop$Params",
    id: "d3abb96331d2e243",
    typeId: 0xd3abb96331d2e243n,
    typeIdHex: "d3abb96331d2e243",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "objectId", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "data" } }
    ] as const,
  };
  static _applyInit(target: AppHooks_Drop$Params, value: $.Init<AppHooks_Drop$Params>): void {
    const init = value;
    {
      const value = init["objectId"];
      if (value !== undefined) {
        if (value instanceof $.Data) {
          target.objectId = value;
        }
        else {
          const bytes = $.dataBytes(value);
          target._initObjectId(bytes.byteLength).copyBuffer(bytes);
        }
      }
    }
  }
  _adoptObjectId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownObjectId(): $.Orphan<$.Data> {
    return $.utils.disown(this.objectId);
  }
  get objectId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasObjectId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initObjectId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set objectId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "AppHooks_Drop$Params_" + super.toString(); }
}
export class AppHooks_Drop$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "drop$Results",
    id: "b34e9b18133a8ea2",
    typeId: 0xb34e9b18133a8ea2n,
    typeIdHex: "b34e9b18133a8ea2",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: AppHooks_Drop$Results, value: $.Init<AppHooks_Drop$Results>): void {
    const init = value;
  }
  toString(): string { return "AppHooks_Drop$Results_" + super.toString(); }
}
export class AppHooks_Drop$Results$Promise {
  pipeline: $.Pipeline<AppHooks_Drop$Results, $.Struct, AppHooks_Drop$Results>;
  constructor(pipeline: $.Pipeline<AppHooks_Drop$Results, $.Struct, AppHooks_Drop$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<AppHooks_Drop$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = AppHooks_Drop$Results, TResult2 = never>(onfulfilled?: ((value: AppHooks_Drop$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<AppHooks_Drop$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<AppHooks_Drop$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class AppHooks$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xa3da9e3e6f3e32cbn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<AppHooks_GetViewInfo$Params, AppHooks_GetViewInfo$Results>,
    $.Method<AppHooks_Restore$Params, AppHooks_Restore$Results>,
    $.Method<AppHooks_Drop$Params, AppHooks_Drop$Results>
  ] = [
    {
      ParamsClass: AppHooks_GetViewInfo$Params,
      ResultsClass: AppHooks_GetViewInfo$Results,
      interfaceId: AppHooks$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppHooks",
      methodName: "getViewInfo",
      paramFields: AppHooks_GetViewInfo$Params._capnp.fields,
      resultFields: AppHooks_GetViewInfo$Results._capnp.fields
    },
    {
      ParamsClass: AppHooks_Restore$Params,
      ResultsClass: AppHooks_Restore$Results,
      interfaceId: AppHooks$Client.interfaceId,
      methodId: 1,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppHooks",
      methodName: "restore",
      paramFields: AppHooks_Restore$Params._capnp.fields,
      resultFields: AppHooks_Restore$Results._capnp.fields
    },
    {
      ParamsClass: AppHooks_Drop$Params,
      ResultsClass: AppHooks_Drop$Results,
      interfaceId: AppHooks$Client.interfaceId,
      methodId: 2,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:AppHooks",
      methodName: "drop",
      paramFields: AppHooks_Drop$Params._capnp.fields,
      resultFields: AppHooks_Drop$Results._capnp.fields
    }
  ];
  getViewInfo(): AppHooks_GetViewInfo$Results$Promise;
  getViewInfo(params: $.Init<AppHooks_GetViewInfo$Params>): AppHooks_GetViewInfo$Results$Promise;
  getViewInfo(paramsFunc: (params: AppHooks_GetViewInfo$Params) => void): AppHooks_GetViewInfo$Results$Promise;
  getViewInfo(params?: $.Initializer<AppHooks_GetViewInfo$Params>): AppHooks_GetViewInfo$Results$Promise {
    const answer = this.client.call({
      method: AppHooks$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: AppHooks_GetViewInfo$Params) => void
          : (target: AppHooks_GetViewInfo$Params) => AppHooks_GetViewInfo$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(AppHooks_GetViewInfo$Results, answer);
    return new AppHooks_GetViewInfo$Results$Promise(pipeline);
  }
  restore(): AppHooks_Restore$Results$Promise;
  restore(params: $.Init<AppHooks_Restore$Params>): AppHooks_Restore$Results$Promise;
  restore(paramsFunc: (params: AppHooks_Restore$Params) => void): AppHooks_Restore$Results$Promise;
  restore(params?: $.Initializer<AppHooks_Restore$Params>): AppHooks_Restore$Results$Promise {
    const answer = this.client.call({
      method: AppHooks$Client.methods[1],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: AppHooks_Restore$Params) => void
          : (target: AppHooks_Restore$Params) => AppHooks_Restore$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(AppHooks_Restore$Results, answer);
    return new AppHooks_Restore$Results$Promise(pipeline);
  }
  drop(): AppHooks_Drop$Results$Promise;
  drop(params: $.Init<AppHooks_Drop$Params>): AppHooks_Drop$Results$Promise;
  drop(paramsFunc: (params: AppHooks_Drop$Params) => void): AppHooks_Drop$Results$Promise;
  drop(params?: $.Initializer<AppHooks_Drop$Params>): AppHooks_Drop$Results$Promise {
    const answer = this.client.call({
      method: AppHooks$Client.methods[2],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: AppHooks_Drop$Params) => void
          : (target: AppHooks_Drop$Params) => AppHooks_Drop$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(AppHooks_Drop$Results, answer);
    return new AppHooks_Drop$Results$Promise(pipeline);
  }
}
$.Registry.register(AppHooks$Client.interfaceId, AppHooks$Client);
export interface AppHooks$Server$Target {
  getViewInfo(params: AppHooks_GetViewInfo$Params, results: AppHooks_GetViewInfo$Results): $.MaybePromise<void | $.Init<AppHooks_GetViewInfo$Results>>;
  restore(params: AppHooks_Restore$Params, results: AppHooks_Restore$Results): $.MaybePromise<void | $.Init<AppHooks_Restore$Results>>;
  drop(params: AppHooks_Drop$Params, results: AppHooks_Drop$Results): $.MaybePromise<void | $.Init<AppHooks_Drop$Results>>;
}
export class AppHooks$Server extends $.Server {
  readonly target: AppHooks$Server$Target;
  constructor(target: AppHooks$Server$Target) {
    super(target, [
      {
        ...AppHooks$Client.methods[0],
        impl: async (params: AppHooks_GetViewInfo$Params, results: AppHooks_GetViewInfo$Results) => {
          const value = await target.getViewInfo(params, results);
          if (value !== undefined) {
            AppHooks_GetViewInfo$Results._applyInit(results, value as $.Init<AppHooks_GetViewInfo$Results>);
          }
        }
      },
      {
        ...AppHooks$Client.methods[1],
        impl: async (params: AppHooks_Restore$Params, results: AppHooks_Restore$Results) => {
          const value = await target.restore(params, results);
          if (value !== undefined) {
            AppHooks_Restore$Results._applyInit(results, value as $.Init<AppHooks_Restore$Results>);
          }
        }
      },
      {
        ...AppHooks$Client.methods[2],
        impl: async (params: AppHooks_Drop$Params, results: AppHooks_Drop$Results) => {
          const value = await target.drop(params, results);
          if (value !== undefined) {
            AppHooks_Drop$Results._applyInit(results, value as $.Init<AppHooks_Drop$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): AppHooks$Client {
    return new AppHooks$Client(this);
  }
}
export class AppHooks extends $.Interface {
  static readonly Client = AppHooks$Client;
  static readonly Server = AppHooks$Server;
  static readonly _capnp = {
    displayName: "AppHooks",
    id: "a3da9e3e6f3e32cb",
    typeId: 0xa3da9e3e6f3e32cbn,
    typeIdHex: "a3da9e3e6f3e32cb",
    size: new $.ObjectSize(0, 0),
    methods: AppHooks$Client.methods,
  };
  toString(): string { return "AppHooks_" + super.toString(); }
}
export class SessionContext_FulfillRequest$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "fulfillRequest$Params",
    id: "dad774a13a5ea885",
    typeId: 0xdad774a13a5ea885n,
    typeIdHex: "dad774a13a5ea885",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "cap", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xd17a48af23601b7cn, typeIdHex: "d17a48af23601b7c", displayName: "Node" } }
    ] as const,
  };
  static _applyInit(target: SessionContext_FulfillRequest$Params, value: $.Init<SessionContext_FulfillRequest$Params>): void {
    const init = value;
    {
      const value = init["cap"];
      if (value !== undefined) {
        target.cap = value;
      }
    }
  }
  get cap(): Node$Client {
    return new Node$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  get capOrNull(): Node$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(0, this))?.getClient() ?? null;
    return client === null ? null : new Node$Client(client);
  }
  set capOrNull(value: Node$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(0, this));
    }
    else {
      this.cap = value;
    }
  }
  set cap(value: Node$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "SessionContext_FulfillRequest$Params_" + super.toString(); }
}
export class SessionContext_FulfillRequest$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "fulfillRequest$Results",
    id: "fedf2733a226251b",
    typeId: 0xfedf2733a226251bn,
    typeIdHex: "fedf2733a226251b",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: SessionContext_FulfillRequest$Results, value: $.Init<SessionContext_FulfillRequest$Results>): void {
    const init = value;
  }
  toString(): string { return "SessionContext_FulfillRequest$Results_" + super.toString(); }
}
export class SessionContext_FulfillRequest$Results$Promise {
  pipeline: $.Pipeline<SessionContext_FulfillRequest$Results, $.Struct, SessionContext_FulfillRequest$Results>;
  constructor(pipeline: $.Pipeline<SessionContext_FulfillRequest$Results, $.Struct, SessionContext_FulfillRequest$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<SessionContext_FulfillRequest$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = SessionContext_FulfillRequest$Results, TResult2 = never>(onfulfilled?: ((value: SessionContext_FulfillRequest$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<SessionContext_FulfillRequest$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<SessionContext_FulfillRequest$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class SessionContext_ClaimRequest$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "claimRequest$Params",
    id: "d77f7210aff2abc8",
    typeId: 0xd77f7210aff2abc8n,
    typeIdHex: "d77f7210aff2abc8",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: SessionContext_ClaimRequest$Params, value: $.Init<SessionContext_ClaimRequest$Params>): void {
    const init = value;
  }
  toString(): string { return "SessionContext_ClaimRequest$Params_" + super.toString(); }
}
export class SessionContext_ClaimRequest$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "claimRequest$Results",
    id: "cc12bb836653bd0a",
    typeId: 0xcc12bb836653bd0an,
    typeIdHex: "cc12bb836653bd0a",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "cap", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xd17a48af23601b7cn, typeIdHex: "d17a48af23601b7c", displayName: "Node" } }
    ] as const,
  };
  static _applyInit(target: SessionContext_ClaimRequest$Results, value: $.Init<SessionContext_ClaimRequest$Results>): void {
    const init = value;
    {
      const value = init["cap"];
      if (value !== undefined) {
        target.cap = value;
      }
    }
  }
  get cap(): Node$Client {
    return new Node$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  get capOrNull(): Node$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(0, this))?.getClient() ?? null;
    return client === null ? null : new Node$Client(client);
  }
  set capOrNull(value: Node$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(0, this));
    }
    else {
      this.cap = value;
    }
  }
  set cap(value: Node$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "SessionContext_ClaimRequest$Results_" + super.toString(); }
}
export class SessionContext_ClaimRequest$Results$Promise {
  pipeline: $.Pipeline<SessionContext_ClaimRequest$Results, $.Struct, SessionContext_ClaimRequest$Results>;
  constructor(pipeline: $.Pipeline<SessionContext_ClaimRequest$Results, $.Struct, SessionContext_ClaimRequest$Results>) {
    this.pipeline = pipeline;
  }
  getCap(): Node$Client {
    return new Node$Client(this.pipeline.getPipeline(Node, 0).client());
  }
  async promise(): Promise<SessionContext_ClaimRequest$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = SessionContext_ClaimRequest$Results, TResult2 = never>(onfulfilled?: ((value: SessionContext_ClaimRequest$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<SessionContext_ClaimRequest$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<SessionContext_ClaimRequest$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class SessionContext$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xb82638dbadc07fe5n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<SessionContext_FulfillRequest$Params, SessionContext_FulfillRequest$Results>,
    $.Method<SessionContext_ClaimRequest$Params, SessionContext_ClaimRequest$Results>
  ] = [
    {
      ParamsClass: SessionContext_FulfillRequest$Params,
      ResultsClass: SessionContext_FulfillRequest$Results,
      interfaceId: SessionContext$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:SessionContext",
      methodName: "fulfillRequest",
      paramFields: SessionContext_FulfillRequest$Params._capnp.fields,
      resultFields: SessionContext_FulfillRequest$Results._capnp.fields
    },
    {
      ParamsClass: SessionContext_ClaimRequest$Params,
      ResultsClass: SessionContext_ClaimRequest$Results,
      interfaceId: SessionContext$Client.interfaceId,
      methodId: 1,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:SessionContext",
      methodName: "claimRequest",
      paramFields: SessionContext_ClaimRequest$Params._capnp.fields,
      resultFields: SessionContext_ClaimRequest$Results._capnp.fields
    }
  ];
  fulfillRequest(): SessionContext_FulfillRequest$Results$Promise;
  fulfillRequest(params: $.Init<SessionContext_FulfillRequest$Params>): SessionContext_FulfillRequest$Results$Promise;
  fulfillRequest(paramsFunc: (params: SessionContext_FulfillRequest$Params) => void): SessionContext_FulfillRequest$Results$Promise;
  fulfillRequest(params?: $.Initializer<SessionContext_FulfillRequest$Params>): SessionContext_FulfillRequest$Results$Promise {
    const answer = this.client.call({
      method: SessionContext$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: SessionContext_FulfillRequest$Params) => void
          : (target: SessionContext_FulfillRequest$Params) => SessionContext_FulfillRequest$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(SessionContext_FulfillRequest$Results, answer);
    return new SessionContext_FulfillRequest$Results$Promise(pipeline);
  }
  claimRequest(): SessionContext_ClaimRequest$Results$Promise;
  claimRequest(params: $.Init<SessionContext_ClaimRequest$Params>): SessionContext_ClaimRequest$Results$Promise;
  claimRequest(paramsFunc: (params: SessionContext_ClaimRequest$Params) => void): SessionContext_ClaimRequest$Results$Promise;
  claimRequest(params?: $.Initializer<SessionContext_ClaimRequest$Params>): SessionContext_ClaimRequest$Results$Promise {
    const answer = this.client.call({
      method: SessionContext$Client.methods[1],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: SessionContext_ClaimRequest$Params) => void
          : (target: SessionContext_ClaimRequest$Params) => SessionContext_ClaimRequest$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(SessionContext_ClaimRequest$Results, answer);
    return new SessionContext_ClaimRequest$Results$Promise(pipeline);
  }
}
$.Registry.register(SessionContext$Client.interfaceId, SessionContext$Client);
export interface SessionContext$Server$Target {
  fulfillRequest(params: SessionContext_FulfillRequest$Params, results: SessionContext_FulfillRequest$Results): $.MaybePromise<void | $.Init<SessionContext_FulfillRequest$Results>>;
  claimRequest(params: SessionContext_ClaimRequest$Params, results: SessionContext_ClaimRequest$Results): $.MaybePromise<void | $.Init<SessionContext_ClaimRequest$Results>>;
}
export class SessionContext$Server extends $.Server {
  readonly target: SessionContext$Server$Target;
  constructor(target: SessionContext$Server$Target) {
    super(target, [
      {
        ...SessionContext$Client.methods[0],
        impl: async (params: SessionContext_FulfillRequest$Params, results: SessionContext_FulfillRequest$Results) => {
          const value = await target.fulfillRequest(params, results);
          if (value !== undefined) {
            SessionContext_FulfillRequest$Results._applyInit(results, value as $.Init<SessionContext_FulfillRequest$Results>);
          }
        }
      },
      {
        ...SessionContext$Client.methods[1],
        impl: async (params: SessionContext_ClaimRequest$Params, results: SessionContext_ClaimRequest$Results) => {
          const value = await target.claimRequest(params, results);
          if (value !== undefined) {
            SessionContext_ClaimRequest$Results._applyInit(results, value as $.Init<SessionContext_ClaimRequest$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): SessionContext$Client {
    return new SessionContext$Client(this);
  }
}
export class SessionContext extends $.Interface {
  static readonly Client = SessionContext$Client;
  static readonly Server = SessionContext$Server;
  static readonly _capnp = {
    displayName: "SessionContext",
    id: "b82638dbadc07fe5",
    typeId: 0xb82638dbadc07fe5n,
    typeIdHex: "b82638dbadc07fe5",
    size: new $.ObjectSize(0, 0),
    methods: SessionContext$Client.methods,
  };
  toString(): string { return "SessionContext_" + super.toString(); }
}
export class SandstormBridge_GetSessionContext$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "getSessionContext$Params",
    id: "d6185b98019425b7",
    typeId: 0xd6185b98019425b7n,
    typeIdHex: "d6185b98019425b7",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: SandstormBridge_GetSessionContext$Params, value: $.Init<SandstormBridge_GetSessionContext$Params>): void {
    const init = value;
  }
  toString(): string { return "SandstormBridge_GetSessionContext$Params_" + super.toString(); }
}
export class SandstormBridge_GetSessionContext$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "getSessionContext$Results",
    id: "87c8ebb952dee654",
    typeId: 0x87c8ebb952dee654n,
    typeIdHex: "87c8ebb952dee654",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "context", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xb82638dbadc07fe5n, typeIdHex: "b82638dbadc07fe5", displayName: "SessionContext" } }
    ] as const,
  };
  static _applyInit(target: SandstormBridge_GetSessionContext$Results, value: $.Init<SandstormBridge_GetSessionContext$Results>): void {
    const init = value;
    {
      const value = init["context"];
      if (value !== undefined) {
        target.context = value;
      }
    }
  }
  get context(): SessionContext$Client {
    return new SessionContext$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  get contextOrNull(): SessionContext$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(0, this))?.getClient() ?? null;
    return client === null ? null : new SessionContext$Client(client);
  }
  set contextOrNull(value: SessionContext$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(0, this));
    }
    else {
      this.context = value;
    }
  }
  set context(value: SessionContext$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "SandstormBridge_GetSessionContext$Results_" + super.toString(); }
}
export class SandstormBridge_GetSessionContext$Results$Promise {
  pipeline: $.Pipeline<SandstormBridge_GetSessionContext$Results, $.Struct, SandstormBridge_GetSessionContext$Results>;
  constructor(pipeline: $.Pipeline<SandstormBridge_GetSessionContext$Results, $.Struct, SandstormBridge_GetSessionContext$Results>) {
    this.pipeline = pipeline;
  }
  getContext(): SessionContext$Client {
    return new SessionContext$Client(this.pipeline.getPipeline(SessionContext, 0).client());
  }
  async promise(): Promise<SandstormBridge_GetSessionContext$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = SandstormBridge_GetSessionContext$Results, TResult2 = never>(onfulfilled?: ((value: SandstormBridge_GetSessionContext$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<SandstormBridge_GetSessionContext$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<SandstormBridge_GetSessionContext$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class SandstormBridge$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0x924ba13008df5c6fn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<SandstormBridge_GetSessionContext$Params, SandstormBridge_GetSessionContext$Results>
  ] = [
    {
      ParamsClass: SandstormBridge_GetSessionContext$Params,
      ResultsClass: SandstormBridge_GetSessionContext$Results,
      interfaceId: SandstormBridge$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/sandstorm-powerbox-flow.capnp:SandstormBridge",
      methodName: "getSessionContext",
      paramFields: SandstormBridge_GetSessionContext$Params._capnp.fields,
      resultFields: SandstormBridge_GetSessionContext$Results._capnp.fields
    }
  ];
  getSessionContext(): SandstormBridge_GetSessionContext$Results$Promise;
  getSessionContext(params: $.Init<SandstormBridge_GetSessionContext$Params>): SandstormBridge_GetSessionContext$Results$Promise;
  getSessionContext(paramsFunc: (params: SandstormBridge_GetSessionContext$Params) => void): SandstormBridge_GetSessionContext$Results$Promise;
  getSessionContext(params?: $.Initializer<SandstormBridge_GetSessionContext$Params>): SandstormBridge_GetSessionContext$Results$Promise {
    const answer = this.client.call({
      method: SandstormBridge$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: SandstormBridge_GetSessionContext$Params) => void
          : (target: SandstormBridge_GetSessionContext$Params) => SandstormBridge_GetSessionContext$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(SandstormBridge_GetSessionContext$Results, answer);
    return new SandstormBridge_GetSessionContext$Results$Promise(pipeline);
  }
}
$.Registry.register(SandstormBridge$Client.interfaceId, SandstormBridge$Client);
export interface SandstormBridge$Server$Target {
  getSessionContext(params: SandstormBridge_GetSessionContext$Params, results: SandstormBridge_GetSessionContext$Results): $.MaybePromise<void | $.Init<SandstormBridge_GetSessionContext$Results>>;
}
export class SandstormBridge$Server extends $.Server {
  readonly target: SandstormBridge$Server$Target;
  constructor(target: SandstormBridge$Server$Target) {
    super(target, [
      {
        ...SandstormBridge$Client.methods[0],
        impl: async (params: SandstormBridge_GetSessionContext$Params, results: SandstormBridge_GetSessionContext$Results) => {
          const value = await target.getSessionContext(params, results);
          if (value !== undefined) {
            SandstormBridge_GetSessionContext$Results._applyInit(results, value as $.Init<SandstormBridge_GetSessionContext$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): SandstormBridge$Client {
    return new SandstormBridge$Client(this);
  }
}
export class SandstormBridge extends $.Interface {
  static readonly Client = SandstormBridge$Client;
  static readonly Server = SandstormBridge$Server;
  static readonly _capnp = {
    displayName: "SandstormBridge",
    id: "924ba13008df5c6f",
    typeId: 0x924ba13008df5c6fn,
    typeIdHex: "924ba13008df5c6f",
    size: new $.ObjectSize(0, 0),
    methods: SandstormBridge$Client.methods,
  };
  toString(): string { return "SandstormBridge_" + super.toString(); }
}
