// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xb597bf4897e54f89n;
export const Person_PhoneNumber_Type = {
  MOBILE: 0,
  HOME: 1,
  WORK: 2
} as const;
export type Person_PhoneNumber_Type = (typeof Person_PhoneNumber_Type)[keyof typeof Person_PhoneNumber_Type];
export class Person_PhoneNumber extends $.Struct {
  static readonly Type = Person_PhoneNumber_Type;
  static readonly _capnp = {
    displayName: "PhoneNumber",
    id: "cba8ed6b45001ccc",
    typeId: 0xcba8ed6b45001cccn,
    typeIdHex: "cba8ed6b45001ccc",
    size: new $.ObjectSize(8, 1),
    fields: [
      { name: "number", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "type", codeOrder: 1, ordinal: 1, kind: "slot", offset: 0, type: { kind: "enum", typeId: 0x98bef1051277b9dfn, typeIdHex: "98bef1051277b9df", displayName: "Type" } }
    ] as const,
  };
  static _applyInit(target: Person_PhoneNumber, value: $.Init<Person_PhoneNumber>): void {
    const init = value as any;
    if (init["number"] !== undefined) {
      target.number = init["number"] as any;
    }
    if (init["type"] !== undefined) {
      target.type = init["type"] as any;
    }
  }
  get number(): string {
    return $.utils.getText(0, this);
  }
  set number(value: string) {
    $.utils.setText(0, value, this);
  }
  get type(): Person_PhoneNumber_Type {
    return $.utils.getUint16(0, this) as Person_PhoneNumber_Type;
  }
  set type(value: Person_PhoneNumber_Type) {
    $.utils.setUint16(0, value, this);
  }
  toString(): string { return "Person_PhoneNumber_" + super.toString(); }
}
export const Person_Employment_Which = {
  UNEMPLOYED: 0,
  EMPLOYER: 1,
  SCHOOL: 2,
  /**
* We assume that a person is only one of these.
*
*/
  SELF_EMPLOYED: 3
} as const;
export type Person_Employment_Which = (typeof Person_Employment_Which)[keyof typeof Person_Employment_Which];
export class Person_Employment extends $.Struct {
  static readonly UNEMPLOYED = Person_Employment_Which.UNEMPLOYED;
  static readonly EMPLOYER = Person_Employment_Which.EMPLOYER;
  static readonly SCHOOL = Person_Employment_Which.SCHOOL;
  static readonly SELF_EMPLOYED = Person_Employment_Which.SELF_EMPLOYED;
  static readonly _capnp = {
    displayName: "employment",
    id: "927f49708287c3b6",
    typeId: 0x927f49708287c3b6n,
    typeIdHex: "927f49708287c3b6",
    size: new $.ObjectSize(8, 4),
    fields: [
      { name: "unemployed", codeOrder: 0, ordinal: 4, discriminantValue: 0, kind: "slot", offset: 0, type: { kind: "void" } },
      { name: "employer", codeOrder: 1, ordinal: 5, discriminantValue: 1, kind: "slot", offset: 3, type: { kind: "text" } },
      { name: "school", codeOrder: 2, ordinal: 6, discriminantValue: 2, kind: "slot", offset: 3, type: { kind: "text" } },
      { name: "selfEmployed", codeOrder: 3, ordinal: 7, discriminantValue: 3, kind: "slot", offset: 0, type: { kind: "void" } }
    ] as const,
  };
  static _applyInit(target: Person_Employment, value: $.Init<Person_Employment>): void {
    const init = value as any;
    if (init["unemployed"] !== undefined) {
      target.unemployed = true;
    }
    if (init["employer"] !== undefined) {
      target.employer = init["employer"] as any;
    }
    if (init["school"] !== undefined) {
      target.school = init["school"] as any;
    }
    if (init["selfEmployed"] !== undefined) {
      target.selfEmployed = true;
    }
  }
  get _isUnemployed(): boolean {
    return $.utils.getUint16(4, this) === 0;
  }
  set unemployed(_: true) {
    $.utils.setUint16(4, 0, this);
  }
  get employer(): string {
    $.utils.testWhich("employer", $.utils.getUint16(4, this), 1, this);
    return $.utils.getText(3, this);
  }
  get _isEmployer(): boolean {
    return $.utils.getUint16(4, this) === 1;
  }
  set employer(value: string) {
    $.utils.setUint16(4, 1, this);
    $.utils.setText(3, value, this);
  }
  get school(): string {
    $.utils.testWhich("school", $.utils.getUint16(4, this), 2, this);
    return $.utils.getText(3, this);
  }
  get _isSchool(): boolean {
    return $.utils.getUint16(4, this) === 2;
  }
  set school(value: string) {
    $.utils.setUint16(4, 2, this);
    $.utils.setText(3, value, this);
  }
  get _isSelfEmployed(): boolean {
    return $.utils.getUint16(4, this) === 3;
  }
  set selfEmployed(_: true) {
    $.utils.setUint16(4, 3, this);
  }
  toString(): string { return "Person_Employment_" + super.toString(); }
  which(): Person_Employment_Which {
    return $.utils.getUint16(4, this) as Person_Employment_Which;
  }
  _set(value: {
    which: "unemployed";
  } | {
    which: "employer";
    value: string;
  } | {
    which: "school";
    value: string;
  } | {
    which: "selfEmployed";
  }): void {
    switch (value.which) {
      case "unemployed": {
        this.unemployed = true;
        return;
      }
      case "employer": {
        this.employer = value.value;
        return;
      }
      case "school": {
        this.school = value.value;
        return;
      }
      case "selfEmployed": {
        this.selfEmployed = true;
        return;
      }
    }
  }
  _match<R>(cases: {
    "unemployed"?: () => R;
    "employer"?: (value: string) => R;
    "school"?: (value: string) => R;
    "selfEmployed"?: () => R;
    _?: (which: Person_Employment_Which) => R;
  }): R {
    const which = this.which();
    switch (which) {
      case 0: {
        const callback = cases["unemployed"];
        if (callback) {
          return callback();
        }
        break;
      }
      case 1: {
        const callback = cases["employer"];
        if (callback) {
          return callback(this.employer);
        }
        break;
      }
      case 2: {
        const callback = cases["school"];
        if (callback) {
          return callback(this.school);
        }
        break;
      }
      case 3: {
        const callback = cases["selfEmployed"];
        if (callback) {
          return callback();
        }
        break;
      }
    }
    if (cases._) {
      return cases._(which);
    }
    throw new Error("Unhandled Person_Employment union case: " + which);
  }
}
export class Person extends $.Struct {
  static readonly PhoneNumber = Person_PhoneNumber;
  static readonly _capnp = {
    displayName: "Person",
    id: "efbbc4e996f07104",
    typeId: 0xefbbc4e996f07104n,
    typeIdHex: "efbbc4e996f07104",
    size: new $.ObjectSize(8, 4),
    fields: [
      { name: "id", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "uint32" } },
      { name: "name", codeOrder: 1, ordinal: 1, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "email", codeOrder: 2, ordinal: 2, kind: "slot", offset: 1, type: { kind: "text" } },
      { name: "phones", codeOrder: 3, ordinal: 3, kind: "slot", offset: 2, type: { kind: "list", elementType: { kind: "struct", typeId: 0xcba8ed6b45001cccn, typeIdHex: "cba8ed6b45001ccc", displayName: "PhoneNumber" } } },
      { name: "employment", codeOrder: 4, ordinal: 4, kind: "group", type: { kind: "group", typeId: 0x927f49708287c3b6n, typeIdHex: "927f49708287c3b6", displayName: "employment" } }
    ] as const,
  };
  static _Phones: $.ListCtor<Person_PhoneNumber>;
  static _applyInit(target: Person, value: $.Init<Person>): void {
    const init = value as any;
    if (init["id"] !== undefined) {
      target.id = init["id"] as any;
    }
    if (init["name"] !== undefined) {
      target.name = init["name"] as any;
    }
    if (init["email"] !== undefined) {
      target.email = init["email"] as any;
    }
    if (init["phones"] !== undefined) {
      if (init["phones"] instanceof $.List) {
        target.phones = init["phones"] as any;
      }
      else {
        const values = Array.isArray(init["phones"]) ? init["phones"] : Array.from(init["phones"] as Iterable<any>);
        const list = target._initPhones(values.length);
        for (let index = 0; index < values.length; index++) {
          const item = values[index];
          if (item instanceof Person_PhoneNumber) {
            list.set(index, item);
          }
          else {
            Person_PhoneNumber._applyInit(list.get(index), item as $.Init<Person_PhoneNumber>);
          }
        }
      }
    }
    if (init["employment"] !== undefined) {
      Person_Employment._applyInit(target._initEmployment(), init["employment"] as $.Init<Person_Employment>);
    }
  }
  get id(): number {
    return $.utils.getUint32(0, this);
  }
  set id(value: number) {
    $.utils.setUint32(0, value, this);
  }
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  get email(): string {
    return $.utils.getText(1, this);
  }
  set email(value: string) {
    $.utils.setText(1, value, this);
  }
  _adoptPhones(value: $.Orphan<$.List<Person_PhoneNumber>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownPhones(): $.Orphan<$.List<Person_PhoneNumber>> {
    return $.utils.disown(this.phones);
  }
  get phones(): $.List<Person_PhoneNumber> {
    return $.utils.getList(2, Person._Phones, this);
  }
  _hasPhones(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initPhones(length: number): $.List<Person_PhoneNumber> {
    return $.utils.initList(2, Person._Phones, length, this);
  }
  set phones(value: $.List<Person_PhoneNumber>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  get employment(): Person_Employment {
    return $.utils.getAs(Person_Employment, this);
  }
  _initEmployment(): Person_Employment {
    return $.utils.getAs(Person_Employment, this);
  }
  toString(): string { return "Person_" + super.toString(); }
}
export class AddressBook extends $.Struct {
  static readonly _capnp = {
    displayName: "AddressBook",
    id: "f724540a01e98224",
    typeId: 0xf724540a01e98224n,
    typeIdHex: "f724540a01e98224",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "people", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "list", elementType: { kind: "struct", typeId: 0xefbbc4e996f07104n, typeIdHex: "efbbc4e996f07104", displayName: "Person" } } }
    ] as const,
  };
  static _People: $.ListCtor<Person>;
  static _applyInit(target: AddressBook, value: $.Init<AddressBook>): void {
    const init = value as any;
    if (init["people"] !== undefined) {
      if (init["people"] instanceof $.List) {
        target.people = init["people"] as any;
      }
      else {
        const values = Array.isArray(init["people"]) ? init["people"] : Array.from(init["people"] as Iterable<any>);
        const list = target._initPeople(values.length);
        for (let index = 0; index < values.length; index++) {
          const item = values[index];
          if (item instanceof Person) {
            list.set(index, item);
          }
          else {
            Person._applyInit(list.get(index), item as $.Init<Person>);
          }
        }
      }
    }
  }
  _adoptPeople(value: $.Orphan<$.List<Person>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownPeople(): $.Orphan<$.List<Person>> {
    return $.utils.disown(this.people);
  }
  get people(): $.List<Person> {
    return $.utils.getList(0, AddressBook._People, this);
  }
  _hasPeople(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initPeople(length: number): $.List<Person> {
    return $.utils.initList(0, AddressBook._People, length, this);
  }
  set people(value: $.List<Person>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "AddressBook_" + super.toString(); }
}
Person._Phones = $.CompositeList(Person_PhoneNumber);
AddressBook._People = $.CompositeList(Person);
