// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xaa89f7261e168017n;
export class SimpleInterface_Subtract$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "subtract$Params",
    id: "888da0aceabad12a",
    typeId: 0x888da0aceabad12an,
    typeIdHex: "888da0aceabad12a",
    size: new $.ObjectSize(8, 0),
    fields: [
      { name: "a", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "int32" } },
      { name: "b", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "int32" } }
    ] as const,
  };
  static _applyInit(target: SimpleInterface_Subtract$Params, value: $.Init<SimpleInterface_Subtract$Params>): void {
    const init = value;
    {
      const value = init["a"];
      if (value !== undefined) {
        target.a = value;
      }
    }
    {
      const value = init["b"];
      if (value !== undefined) {
        target.b = value;
      }
    }
  }
  get a(): number {
    return $.utils.getInt32(0, this);
  }
  set a(value: number) {
    $.utils.setInt32(0, value, this);
  }
  get b(): number {
    return $.utils.getInt32(4, this);
  }
  set b(value: number) {
    $.utils.setInt32(4, value, this);
  }
  toString(): string { return "SimpleInterface_Subtract$Params_" + super.toString(); }
}
export class SimpleInterface_Subtract$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "subtract$Results",
    id: "b0164441a304b38f",
    typeId: 0xb0164441a304b38fn,
    typeIdHex: "b0164441a304b38f",
    size: new $.ObjectSize(8, 0),
    fields: [
      { name: "result", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "int32" } }
    ] as const,
  };
  static _applyInit(target: SimpleInterface_Subtract$Results, value: $.Init<SimpleInterface_Subtract$Results>): void {
    const init = value;
    {
      const value = init["result"];
      if (value !== undefined) {
        target.result = value;
      }
    }
  }
  get result(): number {
    return $.utils.getInt32(0, this);
  }
  set result(value: number) {
    $.utils.setInt32(0, value, this);
  }
  toString(): string { return "SimpleInterface_Subtract$Results_" + super.toString(); }
}
export class SimpleInterface_Subtract$Results$Promise {
  pipeline: $.Pipeline<SimpleInterface_Subtract$Results, $.Struct, SimpleInterface_Subtract$Results>;
  constructor(pipeline: $.Pipeline<SimpleInterface_Subtract$Results, $.Struct, SimpleInterface_Subtract$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<SimpleInterface_Subtract$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = SimpleInterface_Subtract$Results, TResult2 = never>(onfulfilled?: ((value: SimpleInterface_Subtract$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: unknown) => TResult | PromiseLike<TResult>) | null): Promise<SimpleInterface_Subtract$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<SimpleInterface_Subtract$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class SimpleInterface$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xdaf73e960b8928d6n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<SimpleInterface_Subtract$Params, SimpleInterface_Subtract$Results>
  ] = [
    {
      ParamsClass: SimpleInterface_Subtract$Params,
      ResultsClass: SimpleInterface_Subtract$Results,
      interfaceId: SimpleInterface$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/simple-interface.capnp:SimpleInterface",
      methodName: "subtract",
      paramFields: SimpleInterface_Subtract$Params._capnp.fields,
      resultFields: SimpleInterface_Subtract$Results._capnp.fields
    }
  ];
  subtract(): SimpleInterface_Subtract$Results$Promise;
  subtract(params: $.Init<SimpleInterface_Subtract$Params>): SimpleInterface_Subtract$Results$Promise;
  subtract(paramsFunc: (params: SimpleInterface_Subtract$Params) => void): SimpleInterface_Subtract$Results$Promise;
  subtract(params?: $.Initializer<SimpleInterface_Subtract$Params>): SimpleInterface_Subtract$Results$Promise {
    const answer = this.client.call({
      method: SimpleInterface$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: SimpleInterface_Subtract$Params) => void
          : (target: SimpleInterface_Subtract$Params) => SimpleInterface_Subtract$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(SimpleInterface_Subtract$Results, answer);
    return new SimpleInterface_Subtract$Results$Promise(pipeline);
  }
}
$.Registry.register(SimpleInterface$Client.interfaceId, SimpleInterface$Client);
export interface SimpleInterface$Server$Target {
  subtract(params: SimpleInterface_Subtract$Params, results: SimpleInterface_Subtract$Results): $.MaybePromise<void | $.Init<SimpleInterface_Subtract$Results>>;
}
export class SimpleInterface$Server extends $.Server {
  readonly target: SimpleInterface$Server$Target;
  constructor(target: SimpleInterface$Server$Target) {
    super(target, [
      {
        ...SimpleInterface$Client.methods[0],
        impl: async (params: SimpleInterface_Subtract$Params, results: SimpleInterface_Subtract$Results) => {
          const value = await target.subtract(params, results);
          if (value !== undefined) {
            SimpleInterface_Subtract$Results._applyInit(results, value as $.Init<SimpleInterface_Subtract$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): SimpleInterface$Client {
    return new SimpleInterface$Client(this);
  }
}
export class SimpleInterface extends $.Interface {
  static readonly Client = SimpleInterface$Client;
  static readonly Server = SimpleInterface$Server;
  static readonly _capnp = {
    displayName: "SimpleInterface",
    id: "daf73e960b8928d6",
    typeId: 0xdaf73e960b8928d6n,
    typeIdHex: "daf73e960b8928d6",
    size: new $.ObjectSize(0, 0),
    methods: SimpleInterface$Client.methods,
  };
  toString(): string { return "SimpleInterface_" + super.toString(); }
}
