// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xc81a48fa54bfdd1fn;
export class Upgrade extends $.Struct {
  static readonly _capnp = {
    displayName: "Upgrade",
    id: "8fa95f1989e267fb",
    typeId: 0x8fa95f1989e267fbn,
    typeIdHex: "8fa95f1989e267fb",
    size: new $.ObjectSize(8, 4),
    fields: [
      { name: "legacyName", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "legacyId", codeOrder: 1, ordinal: 1, kind: "slot", offset: 0, type: { kind: "int32" } },
      { name: "selfReference", codeOrder: 2, ordinal: 2, kind: "slot", offset: 1, type: { kind: "struct", typeId: 0x8fa95f1989e267fbn, typeIdHex: "8fa95f1989e267fb", displayName: "Upgrade" } },
      { name: "selfReferences", codeOrder: 3, ordinal: 3, kind: "slot", offset: 2, type: { kind: "list", elementType: { kind: "struct", typeId: 0x8fa95f1989e267fbn, typeIdHex: "8fa95f1989e267fb", displayName: "Upgrade" } } },
      { name: "newHotnessName", codeOrder: 4, ordinal: 4, kind: "slot", offset: 3, type: { kind: "text" } },
      { name: "newHotnessId", codeOrder: 5, ordinal: 5, kind: "slot", offset: 1, type: { kind: "int32" } }
    ] as const,
  };
  static _SelfReferences: $.ListCtor<Upgrade>;
  static _applyInit(target: Upgrade, value: $.Init<Upgrade>): void {
    const init = value as any;
    if (init["legacyName"] !== undefined) {
      target.legacyName = init["legacyName"] as any;
    }
    if (init["legacyId"] !== undefined) {
      target.legacyId = init["legacyId"] as any;
    }
    if (init["selfReference"] !== undefined) {
      if (init["selfReference"] instanceof Upgrade) {
        target.selfReference = init["selfReference"] as Upgrade;
      }
      else {
        Upgrade._applyInit(target._initSelfReference(), init["selfReference"] as $.Init<Upgrade>);
      }
    }
    if (init["selfReferences"] !== undefined) {
      if (init["selfReferences"] instanceof $.List) {
        target.selfReferences = init["selfReferences"] as any;
      }
      else {
        const values = Array.isArray(init["selfReferences"]) ? init["selfReferences"] : Array.from(init["selfReferences"] as Iterable<any>);
        const list = target._initSelfReferences(values.length);
        for (let index = 0; index < values.length; index++) {
          const item = values[index];
          if (item instanceof Upgrade) {
            list.set(index, item);
          }
          else {
            Upgrade._applyInit(list.get(index), item as $.Init<Upgrade>);
          }
        }
      }
    }
    if (init["newHotnessName"] !== undefined) {
      target.newHotnessName = init["newHotnessName"] as any;
    }
    if (init["newHotnessId"] !== undefined) {
      target.newHotnessId = init["newHotnessId"] as any;
    }
  }
  get legacyName(): string {
    return $.utils.getText(0, this);
  }
  set legacyName(value: string) {
    $.utils.setText(0, value, this);
  }
  get legacyId(): number {
    return $.utils.getInt32(0, this);
  }
  set legacyId(value: number) {
    $.utils.setInt32(0, value, this);
  }
  _adoptSelfReference(value: $.Orphan<Upgrade>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownSelfReference(): $.Orphan<Upgrade> {
    return $.utils.disown(this.selfReference);
  }
  get selfReference(): Upgrade {
    return $.utils.getStruct(1, Upgrade, this);
  }
  _hasSelfReference(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initSelfReference(): Upgrade {
    return $.utils.initStructAt(1, Upgrade, this);
  }
  set selfReference(value: Upgrade) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  _adoptSelfReferences(value: $.Orphan<$.List<Upgrade>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownSelfReferences(): $.Orphan<$.List<Upgrade>> {
    return $.utils.disown(this.selfReferences);
  }
  get selfReferences(): $.List<Upgrade> {
    return $.utils.getList(2, Upgrade._SelfReferences, this);
  }
  _hasSelfReferences(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initSelfReferences(length: number): $.List<Upgrade> {
    return $.utils.initList(2, Upgrade._SelfReferences, length, this);
  }
  set selfReferences(value: $.List<Upgrade>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  get newHotnessName(): string {
    return $.utils.getText(3, this);
  }
  set newHotnessName(value: string) {
    $.utils.setText(3, value, this);
  }
  get newHotnessId(): number {
    return $.utils.getInt32(4, this);
  }
  set newHotnessId(value: number) {
    $.utils.setInt32(4, value, this);
  }
  toString(): string { return "Upgrade_" + super.toString(); }
}
Upgrade._SelfReferences = $.CompositeList(Upgrade);
