// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xc81a48fa54bfdd1en;
export class Upgrade extends $.Struct {
  static readonly _capnp = {
    displayName: "Upgrade",
    id: "b274c862a78a049c",
    typeId: 0xb274c862a78a049cn,
    typeIdHex: "b274c862a78a049c",
    size: new $.ObjectSize(8, 3),
    fields: [
      { name: "legacyName", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "legacyId", codeOrder: 1, ordinal: 1, kind: "slot", offset: 0, type: { kind: "int32" } },
      { name: "selfReference", codeOrder: 2, ordinal: 2, kind: "slot", offset: 1, type: { kind: "struct", typeId: 0xb274c862a78a049cn, typeIdHex: "b274c862a78a049c", displayName: "Upgrade" } },
      { name: "selfReferences", codeOrder: 3, ordinal: 3, kind: "slot", offset: 2, type: { kind: "list", elementType: { kind: "struct", typeId: 0xb274c862a78a049cn, typeIdHex: "b274c862a78a049c", displayName: "Upgrade" } } }
    ] as const,
  };
  static _SelfReferences: $.ListCtor<Upgrade>;
  static _applyInit(target: Upgrade, value: $.Init<Upgrade>): void {
    const init = value as any;
    {
      const value = init["legacyName"];
      if (value !== undefined) {
        target.legacyName = value as any;
      }
    }
    {
      const value = init["legacyId"];
      if (value !== undefined) {
        target.legacyId = value as any;
      }
    }
    {
      const value = init["selfReference"];
      if (value !== undefined) {
        if (value instanceof Upgrade) {
          target.selfReference = value as Upgrade;
        }
        else {
          Upgrade._applyInit(target._initSelfReference(), value as $.Init<Upgrade>);
        }
      }
    }
    {
      const value = init["selfReferences"];
      if (value !== undefined) {
        if (value instanceof $.List) {
          target.selfReferences = value as any;
        }
        else {
          const values = Array.isArray(value) ? value : Array.from(value as Iterable<any>);
          const list = target._initSelfReferences(values.length);
          for (let index = 0; index < values.length; index++) {
            const item = values[index];
            if (item instanceof Upgrade) {
              list.set(index, item);
            }
            else {
              Upgrade._applyInit(list.get(index), item as $.Init<Upgrade>);
            }
          }
        }
      }
    }
  }
  get legacyName(): string {
    return $.utils.getText(0, this);
  }
  set legacyName(value: string) {
    $.utils.setText(0, value, this);
  }
  get legacyId(): number {
    return $.utils.getInt32(0, this);
  }
  set legacyId(value: number) {
    $.utils.setInt32(0, value, this);
  }
  _adoptSelfReference(value: $.Orphan<Upgrade>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownSelfReference(): $.Orphan<Upgrade> {
    return $.utils.disown(this.selfReference);
  }
  get selfReference(): Upgrade {
    return $.utils.getStruct(1, Upgrade, this);
  }
  _hasSelfReference(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initSelfReference(): Upgrade {
    return $.utils.initStructAt(1, Upgrade, this);
  }
  set selfReference(value: Upgrade) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  _adoptSelfReferences(value: $.Orphan<$.List<Upgrade>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownSelfReferences(): $.Orphan<$.List<Upgrade>> {
    return $.utils.disown(this.selfReferences);
  }
  get selfReferences(): $.List<Upgrade> {
    return $.utils.getList(2, Upgrade._SelfReferences, this);
  }
  _hasSelfReferences(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initSelfReferences(length: number): $.List<Upgrade> {
    return $.utils.initList(2, Upgrade._SelfReferences, length, this);
  }
  set selfReferences(value: $.List<Upgrade>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  toString(): string { return "Upgrade_" + super.toString(); }
}
Upgrade._SelfReferences = $.CompositeList(Upgrade);
