// This file has been automatically generated by capnp-es.
import * as $ from "./capnp-runtime-shim.js";
export const _capnpFileId = 0xdac2d161ba5d99e2n;
export class UiSession_Ping$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "ping$Params",
    id: "ac3ec02cfd0cf092",
    typeId: 0xac3ec02cfd0cf092n,
    typeIdHex: "ac3ec02cfd0cf092",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: UiSession_Ping$Params, value: $.Init<UiSession_Ping$Params>): void {
    const init = value;
  }
  toString(): string { return "UiSession_Ping$Params_" + super.toString(); }
}
export class UiSession_Ping$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "ping$Results",
    id: "dd7a68c7d82e1179",
    typeId: 0xdd7a68c7d82e1179n,
    typeIdHex: "dd7a68c7d82e1179",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: UiSession_Ping$Results, value: $.Init<UiSession_Ping$Results>): void {
    const init = value;
  }
  toString(): string { return "UiSession_Ping$Results_" + super.toString(); }
}
export class UiSession_Ping$Results$Promise {
  pipeline: $.Pipeline<UiSession_Ping$Results, $.Struct, UiSession_Ping$Results>;
  constructor(pipeline: $.Pipeline<UiSession_Ping$Results, $.Struct, UiSession_Ping$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<UiSession_Ping$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = UiSession_Ping$Results, TResult2 = never>(onfulfilled?: ((value: UiSession_Ping$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null): Promise<UiSession_Ping$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<UiSession_Ping$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class UiSession$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xe956d2d30f864ea0n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<UiSession_Ping$Params, UiSession_Ping$Results>
  ] = [
    {
      ParamsClass: UiSession_Ping$Params,
      ResultsClass: UiSession_Ping$Results,
      interfaceId: UiSession$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/web-session-interop.capnp:UiSession",
      methodName: "ping",
      paramFields: UiSession_Ping$Params._capnp.fields,
      resultFields: UiSession_Ping$Results._capnp.fields
    }
  ];
  ping(): UiSession_Ping$Results$Promise;
  ping(params: $.Init<UiSession_Ping$Params>): UiSession_Ping$Results$Promise;
  ping(paramsFunc: (params: UiSession_Ping$Params) => void): UiSession_Ping$Results$Promise;
  ping(params?: $.Initializer<UiSession_Ping$Params>): UiSession_Ping$Results$Promise {
    const answer = this.client.call({
      method: UiSession$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: UiSession_Ping$Params) => void
          : (target: UiSession_Ping$Params) => UiSession_Ping$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(UiSession_Ping$Results, answer);
    return new UiSession_Ping$Results$Promise(pipeline);
  }
}
$.Registry.register(UiSession$Client.interfaceId, UiSession$Client);
export interface UiSession$Server$Target {
  ping(params: UiSession_Ping$Params, results: UiSession_Ping$Results): $.MaybePromise<void | $.Init<UiSession_Ping$Results>>;
}
export class UiSession$Server extends $.Server {
  readonly target: UiSession$Server$Target;
  constructor(target: UiSession$Server$Target) {
    super(target, [
      {
        ...UiSession$Client.methods[0],
        impl: async (params: UiSession_Ping$Params, results: UiSession_Ping$Results) => {
          const value = await target.ping(params, results);
          if (value !== undefined) {
            UiSession_Ping$Results._applyInit(results, value as $.Init<UiSession_Ping$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): UiSession$Client {
    return new UiSession$Client(this);
  }
}
export class UiSession extends $.Interface {
  static readonly Client = UiSession$Client;
  static readonly Server = UiSession$Server;
  static readonly _capnp = {
    displayName: "UiSession",
    id: "e956d2d30f864ea0",
    typeId: 0xe956d2d30f864ea0n,
    typeIdHex: "e956d2d30f864ea0",
    size: new $.ObjectSize(0, 0),
    methods: UiSession$Client.methods,
  };
  toString(): string { return "UiSession_" + super.toString(); }
}
export class ByteStream_Write$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "write$Params",
    id: "b361ee90c6e155ac",
    typeId: 0xb361ee90c6e155acn,
    typeIdHex: "b361ee90c6e155ac",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "data", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "data" } }
    ] as const,
  };
  static _applyInit(target: ByteStream_Write$Params, value: $.Init<ByteStream_Write$Params>): void {
    const init = value;
    {
      const value = init["data"];
      if (value !== undefined) {
        if (value instanceof $.Data) {
          target.data = value;
        }
        else {
          const bytes = $.dataBytes(value);
          target._initData(bytes.byteLength).copyBuffer(bytes);
        }
      }
    }
  }
  _adoptData(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData(): $.Orphan<$.Data> {
    return $.utils.disown(this.data);
  }
  get data(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasData(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set data(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "ByteStream_Write$Params_" + super.toString(); }
}
export class ByteStream_Write$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "write$Results",
    id: "af2f1597810827db",
    typeId: 0xaf2f1597810827dbn,
    typeIdHex: "af2f1597810827db",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: ByteStream_Write$Results, value: $.Init<ByteStream_Write$Results>): void {
    const init = value;
  }
  toString(): string { return "ByteStream_Write$Results_" + super.toString(); }
}
export class ByteStream_Write$Results$Promise {
  pipeline: $.Pipeline<ByteStream_Write$Results, $.Struct, ByteStream_Write$Results>;
  constructor(pipeline: $.Pipeline<ByteStream_Write$Results, $.Struct, ByteStream_Write$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<ByteStream_Write$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = ByteStream_Write$Results, TResult2 = never>(onfulfilled?: ((value: ByteStream_Write$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null): Promise<ByteStream_Write$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<ByteStream_Write$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class ByteStream_Done$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "done$Params",
    id: "cad0dc61a605ea04",
    typeId: 0xcad0dc61a605ea04n,
    typeIdHex: "cad0dc61a605ea04",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: ByteStream_Done$Params, value: $.Init<ByteStream_Done$Params>): void {
    const init = value;
  }
  toString(): string { return "ByteStream_Done$Params_" + super.toString(); }
}
export class ByteStream_Done$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "done$Results",
    id: "a262a4bced7339e8",
    typeId: 0xa262a4bced7339e8n,
    typeIdHex: "a262a4bced7339e8",
    size: new $.ObjectSize(0, 0),
    fields: [] as const,
  };
  static _applyInit(target: ByteStream_Done$Results, value: $.Init<ByteStream_Done$Results>): void {
    const init = value;
  }
  toString(): string { return "ByteStream_Done$Results_" + super.toString(); }
}
export class ByteStream_Done$Results$Promise {
  pipeline: $.Pipeline<ByteStream_Done$Results, $.Struct, ByteStream_Done$Results>;
  constructor(pipeline: $.Pipeline<ByteStream_Done$Results, $.Struct, ByteStream_Done$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<ByteStream_Done$Results> {
    return await this.pipeline.struct();
  }
  then<TResult1 = ByteStream_Done$Results, TResult2 = never>(onfulfilled?: ((value: ByteStream_Done$Results) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null): Promise<ByteStream_Done$Results | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<ByteStream_Done$Results> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class ByteStream$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0xf8adf062f19cb829n;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<ByteStream_Write$Params, ByteStream_Write$Results>,
    $.Method<ByteStream_Done$Params, ByteStream_Done$Results>
  ] = [
    {
      ParamsClass: ByteStream_Write$Params,
      ResultsClass: ByteStream_Write$Results,
      interfaceId: ByteStream$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/web-session-interop.capnp:ByteStream",
      methodName: "write",
      paramFields: ByteStream_Write$Params._capnp.fields,
      resultFields: ByteStream_Write$Results._capnp.fields
    },
    {
      ParamsClass: ByteStream_Done$Params,
      ResultsClass: ByteStream_Done$Results,
      interfaceId: ByteStream$Client.interfaceId,
      methodId: 1,
      interfaceName: "test/fixtures/web-session-interop.capnp:ByteStream",
      methodName: "done",
      paramFields: ByteStream_Done$Params._capnp.fields,
      resultFields: ByteStream_Done$Results._capnp.fields
    }
  ];
  write(): ByteStream_Write$Results$Promise;
  write(params: $.Init<ByteStream_Write$Params>): ByteStream_Write$Results$Promise;
  write(paramsFunc: (params: ByteStream_Write$Params) => void): ByteStream_Write$Results$Promise;
  write(params?: $.Initializer<ByteStream_Write$Params>): ByteStream_Write$Results$Promise {
    const answer = this.client.call({
      method: ByteStream$Client.methods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: ByteStream_Write$Params) => void
          : (target: ByteStream_Write$Params) => ByteStream_Write$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(ByteStream_Write$Results, answer);
    return new ByteStream_Write$Results$Promise(pipeline);
  }
  done(): ByteStream_Done$Results$Promise;
  done(params: $.Init<ByteStream_Done$Params>): ByteStream_Done$Results$Promise;
  done(paramsFunc: (params: ByteStream_Done$Params) => void): ByteStream_Done$Results$Promise;
  done(params?: $.Initializer<ByteStream_Done$Params>): ByteStream_Done$Results$Promise {
    const answer = this.client.call({
      method: ByteStream$Client.methods[1],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: ByteStream_Done$Params) => void
          : (target: ByteStream_Done$Params) => ByteStream_Done$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(ByteStream_Done$Results, answer);
    return new ByteStream_Done$Results$Promise(pipeline);
  }
}
$.Registry.register(ByteStream$Client.interfaceId, ByteStream$Client);
export interface ByteStream$Server$Target {
  write(params: ByteStream_Write$Params, results: ByteStream_Write$Results): $.MaybePromise<void | $.Init<ByteStream_Write$Results>>;
  done(params: ByteStream_Done$Params, results: ByteStream_Done$Results): $.MaybePromise<void | $.Init<ByteStream_Done$Results>>;
}
export class ByteStream$Server extends $.Server {
  readonly target: ByteStream$Server$Target;
  constructor(target: ByteStream$Server$Target) {
    super(target, [
      {
        ...ByteStream$Client.methods[0],
        impl: async (params: ByteStream_Write$Params, results: ByteStream_Write$Results) => {
          const value = await target.write(params, results);
          if (value !== undefined) {
            ByteStream_Write$Results._applyInit(results, value as $.Init<ByteStream_Write$Results>);
          }
        }
      },
      {
        ...ByteStream$Client.methods[1],
        impl: async (params: ByteStream_Done$Params, results: ByteStream_Done$Results) => {
          const value = await target.done(params, results);
          if (value !== undefined) {
            ByteStream_Done$Results._applyInit(results, value as $.Init<ByteStream_Done$Results>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): ByteStream$Client {
    return new ByteStream$Client(this);
  }
}
export class ByteStream extends $.Interface {
  static readonly Client = ByteStream$Client;
  static readonly Server = ByteStream$Server;
  static readonly _capnp = {
    displayName: "ByteStream",
    id: "f8adf062f19cb829",
    typeId: 0xf8adf062f19cb829n,
    typeIdHex: "f8adf062f19cb829",
    size: new $.ObjectSize(0, 0),
    methods: ByteStream$Client.methods,
  };
  toString(): string { return "ByteStream_" + super.toString(); }
}
export class WebSession_Get$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "get$Params",
    id: "c26615563a9c4b10",
    typeId: 0xc26615563a9c4b10n,
    typeIdHex: "c26615563a9c4b10",
    size: new $.ObjectSize(8, 2),
    fields: [
      { name: "path", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "context", codeOrder: 1, ordinal: 1, kind: "slot", offset: 1, type: { kind: "struct", typeId: 0xb26193c077cc23a3n, typeIdHex: "b26193c077cc23a3", displayName: "Context" } },
      { name: "ignoreBody", codeOrder: 2, ordinal: 2, kind: "slot", offset: 0, type: { kind: "bool" } }
    ] as const,
  };
  static _applyInit(target: WebSession_Get$Params, value: $.Init<WebSession_Get$Params>): void {
    const init = value;
    {
      const value = init["path"];
      if (value !== undefined) {
        target.path = value;
      }
    }
    {
      const value = init["context"];
      if (value !== undefined) {
        if (value instanceof Context) {
          target.context = value;
        }
        else {
          Context._applyInit(target._initContext(), value as $.Init<Context>);
        }
      }
    }
    {
      const value = init["ignoreBody"];
      if (value !== undefined) {
        target.ignoreBody = value;
      }
    }
  }
  get path(): string {
    return $.utils.getText(0, this);
  }
  set path(value: string) {
    $.utils.setText(0, value, this);
  }
  _adoptContext(value: $.Orphan<Context>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownContext(): $.Orphan<Context> {
    return $.utils.disown(this.context);
  }
  get context(): Context {
    return $.utils.getStruct(1, Context, this);
  }
  _hasContext(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initContext(): Context {
    return $.utils.initStructAt(1, Context, this);
  }
  set context(value: Context) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  get ignoreBody(): boolean {
    return $.utils.getBit(0, this);
  }
  set ignoreBody(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  toString(): string { return "WebSession_Get$Params_" + super.toString(); }
}
export const Response_Content_Body_Which = {
  BYTES: 0,
  STREAM: 1
} as const;
export type Response_Content_Body_Which = (typeof Response_Content_Body_Which)[keyof typeof Response_Content_Body_Which];
export class Response_Content_Body extends $.Struct {
  static readonly BYTES = Response_Content_Body_Which.BYTES;
  static readonly STREAM = Response_Content_Body_Which.STREAM;
  static readonly _capnp = {
    displayName: "body",
    id: "eb6dd7d2f07f86df",
    typeId: 0xeb6dd7d2f07f86dfn,
    typeIdHex: "eb6dd7d2f07f86df",
    size: new $.ObjectSize(8, 2),
    fields: [
      { name: "bytes", codeOrder: 0, ordinal: 2, discriminantValue: 0, kind: "slot", offset: 1, type: { kind: "data" } },
      { name: "stream", codeOrder: 1, ordinal: 3, discriminantValue: 1, kind: "slot", offset: 1, type: { kind: "interface", typeId: 0xf8adf062f19cb829n, typeIdHex: "f8adf062f19cb829", displayName: "ByteStream" } }
    ] as const,
  };
  static _applyInit(target: Response_Content_Body, value: $.Init<Response_Content_Body>): void {
    const init = value;
    {
      const value = init["bytes"];
      if (value !== undefined) {
        if (value instanceof $.Data) {
          target.bytes = value;
        }
        else {
          const bytes = $.dataBytes(value);
          target._initBytes(bytes.byteLength).copyBuffer(bytes);
        }
      }
    }
    {
      const value = init["stream"];
      if (value !== undefined) {
        target.stream = value;
      }
    }
  }
  _adoptBytes(value: $.Orphan<$.Data>): void {
    $.utils.setUint16(2, 0, this);
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownBytes(): $.Orphan<$.Data> {
    return $.utils.disown(this.bytes);
  }
  get bytes(): $.Data {
    $.utils.testWhich("bytes", $.utils.getUint16(2, this), 0, this);
    return $.utils.getData(1, this);
  }
  _hasBytes(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initBytes(length: number): $.Data {
    $.utils.setUint16(2, 0, this);
    return $.utils.initData(1, length, this);
  }
  get _isBytes(): boolean {
    return $.utils.getUint16(2, this) === 0;
  }
  set bytes(value: $.Data) {
    $.utils.setUint16(2, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  get stream(): ByteStream$Client {
    $.utils.testWhich("stream", $.utils.getUint16(2, this), 1, this);
    return new ByteStream$Client($.utils.getInterfaceClientOrNullAt(1, this));
  }
  get streamOrNull(): ByteStream$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(1, this))?.getClient() ?? null;
    return client === null ? null : new ByteStream$Client(client);
  }
  set streamOrNull(value: ByteStream$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(1, this));
    }
    else {
      this.stream = value;
    }
  }
  get _isStream(): boolean {
    return $.utils.getUint16(2, this) === 1;
  }
  set stream(value: ByteStream$Client) {
    $.utils.setUint16(2, 1, this);
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(1, this));
  }
  toString(): string { return "Response_Content_Body_" + super.toString(); }
  which(): Response_Content_Body_Which {
    return $.utils.getUint16(2, this) as Response_Content_Body_Which;
  }
  _set(value: {
    which: "bytes";
    value: $.Data;
  } | {
    which: "stream";
    value: ByteStream$Client;
  }): void {
    switch (value.which) {
      case "bytes": {
        this.bytes = value.value;
        return;
      }
      case "stream": {
        this.stream = value.value;
        return;
      }
    }
  }
  _match<R>(cases: {
    "bytes"?: (value: $.Data) => R;
    "stream"?: (value: ByteStream$Client) => R;
    _?: (which: Response_Content_Body_Which) => R;
  }): R {
    const which = this.which();
    switch (which) {
      case 0: {
        const callback = cases["bytes"];
        if (callback) {
          return callback(this.bytes);
        }
        break;
      }
      case 1: {
        const callback = cases["stream"];
        if (callback) {
          return callback(this.stream);
        }
        break;
      }
    }
    if (cases._) {
      return cases._(which);
    }
    throw new Error("Unhandled Response_Content_Body union case: " + which);
  }
}
export class Response_Content extends $.Struct {
  static readonly _capnp = {
    displayName: "content",
    id: "c46c77a511751d18",
    typeId: 0xc46c77a511751d18n,
    typeIdHex: "c46c77a511751d18",
    size: new $.ObjectSize(8, 2),
    fields: [
      { name: "statusCode", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "uint16" } },
      { name: "mimeType", codeOrder: 1, ordinal: 1, kind: "slot", offset: 0, type: { kind: "text" } },
      { name: "body", codeOrder: 2, ordinal: 2, kind: "group", type: { kind: "group", typeId: 0xeb6dd7d2f07f86dfn, typeIdHex: "eb6dd7d2f07f86df", displayName: "body" } }
    ] as const,
  };
  static _applyInit(target: Response_Content, value: $.Init<Response_Content>): void {
    const init = value;
    {
      const value = init["statusCode"];
      if (value !== undefined) {
        target.statusCode = value;
      }
    }
    {
      const value = init["mimeType"];
      if (value !== undefined) {
        target.mimeType = value;
      }
    }
    {
      const value = init["body"];
      if (value !== undefined) {
        Response_Content_Body._applyInit(target._initBody(), value as $.Init<Response_Content_Body>);
      }
    }
  }
  get statusCode(): number {
    return $.utils.getUint16(0, this);
  }
  set statusCode(value: number) {
    $.utils.setUint16(0, value, this);
  }
  get mimeType(): string {
    return $.utils.getText(0, this);
  }
  set mimeType(value: string) {
    $.utils.setText(0, value, this);
  }
  get body(): Response_Content_Body {
    return $.utils.getAs(Response_Content_Body, this);
  }
  _initBody(): Response_Content_Body {
    return $.utils.getAs(Response_Content_Body, this);
  }
  toString(): string { return "Response_Content_" + super.toString(); }
}
export const Response_Which = {
  CONTENT: 0,
  NO_CONTENT: 1
} as const;
export type Response_Which = (typeof Response_Which)[keyof typeof Response_Which];
export class Response extends $.Struct {
  static readonly CONTENT = Response_Which.CONTENT;
  static readonly NO_CONTENT = Response_Which.NO_CONTENT;
  static readonly _capnp = {
    displayName: "Response",
    id: "918e53feab3beb6c",
    typeId: 0x918e53feab3beb6cn,
    typeIdHex: "918e53feab3beb6c",
    size: new $.ObjectSize(8, 2),
    fields: [
      { name: "content", codeOrder: 0, ordinal: 0, discriminantValue: 0, kind: "group", type: { kind: "group", typeId: 0xc46c77a511751d18n, typeIdHex: "c46c77a511751d18", displayName: "content" } },
      { name: "noContent", codeOrder: 1, ordinal: 4, discriminantValue: 1, kind: "slot", offset: 0, type: { kind: "void" } }
    ] as const,
  };
  static _applyInit(target: Response, value: $.Init<Response>): void {
    const init = value;
    {
      const value = init["content"];
      if (value !== undefined) {
        Response_Content._applyInit(target._initContent(), value as $.Init<Response_Content>);
      }
    }
    {
      const value = (init as {
        "noContent"?: true;
      })["noContent"];
      if (value !== undefined) {
        target.noContent = true;
      }
    }
  }
  get content(): Response_Content {
    $.utils.testWhich("content", $.utils.getUint16(4, this), 0, this);
    return $.utils.getAs(Response_Content, this);
  }
  _initContent(): Response_Content {
    $.utils.setUint16(4, 0, this);
    return $.utils.getAs(Response_Content, this);
  }
  get _isContent(): boolean {
    return $.utils.getUint16(4, this) === 0;
  }
  set content(_: true) {
    $.utils.setUint16(4, 0, this);
  }
  get _isNoContent(): boolean {
    return $.utils.getUint16(4, this) === 1;
  }
  set noContent(_: true) {
    $.utils.setUint16(4, 1, this);
  }
  toString(): string { return "Response_" + super.toString(); }
  which(): Response_Which {
    return $.utils.getUint16(4, this) as Response_Which;
  }
  _set(value: {
    which: "content";
  } | {
    which: "noContent";
  }): void {
    switch (value.which) {
      case "content": {
        this.content = true;
        return;
      }
      case "noContent": {
        this.noContent = true;
        return;
      }
    }
  }
  _match<R>(cases: {
    "content"?: (value: Response_Content) => R;
    "noContent"?: () => R;
    _?: (which: Response_Which) => R;
  }): R {
    const which = this.which();
    switch (which) {
      case 0: {
        const callback = cases["content"];
        if (callback) {
          return callback(this.content);
        }
        break;
      }
      case 1: {
        const callback = cases["noContent"];
        if (callback) {
          return callback();
        }
        break;
      }
    }
    if (cases._) {
      return cases._(which);
    }
    throw new Error("Unhandled Response union case: " + which);
  }
}
export class Response$Promise {
  pipeline: $.Pipeline<Response, $.Struct, Response>;
  constructor(pipeline: $.Pipeline<Response, $.Struct, Response>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<Response> {
    return await this.pipeline.struct();
  }
  then<TResult1 = Response, TResult2 = never>(onfulfilled?: ((value: Response) => TResult1 | PromiseLike<TResult1>) | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null): Promise<TResult1 | TResult2> {
    return this.promise().then(onfulfilled, onrejected);
  }
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null): Promise<Response | TResult> {
    return this.promise().catch(onrejected);
  }
  finally(onfinally?: (() => void) | null): Promise<Response> {
    return this.promise().finally(onfinally ?? undefined);
  }
}
export class WebSession$Client {
  client: $.Client;
  static readonly interfaceId: bigint = 0x90d73605e02f91bbn;
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly ownMethods: [
    $.Method<WebSession_Get$Params, Response>
  ] = [
    {
      ParamsClass: WebSession_Get$Params,
      ResultsClass: Response,
      interfaceId: WebSession$Client.interfaceId,
      methodId: 0,
      interfaceName: "test/fixtures/web-session-interop.capnp:WebSession",
      methodName: "get",
      paramFields: WebSession_Get$Params._capnp.fields,
      resultFields: Response._capnp.fields
    }
  ];
  static readonly methods: $.Method<$.Struct, $.Struct>[] = [
    ...UiSession$Client.methods,
    ...WebSession$Client.ownMethods
  ];
  ping(...args: Parameters<UiSession$Client["ping"]>): ReturnType<UiSession$Client["ping"]> {
    return UiSession$Client.prototype.ping.apply(this, args);
  }
  get(): Response$Promise;
  get(params: $.Init<WebSession_Get$Params>): Response$Promise;
  get(paramsFunc: (params: WebSession_Get$Params) => void): Response$Promise;
  get(params?: $.Initializer<WebSession_Get$Params>): Response$Promise {
    const answer = this.client.call({
      method: WebSession$Client.ownMethods[0],
      paramsFunc: params === undefined
        ? undefined
        : typeof params === "function"
          ? params as (target: WebSession_Get$Params) => void
          : (target: WebSession_Get$Params) => WebSession_Get$Params._applyInit(target, params)
    });
    const pipeline = new $.Pipeline(Response, answer);
    return new Response$Promise(pipeline);
  }
}
$.Registry.register(WebSession$Client.interfaceId, WebSession$Client);
export interface WebSession$Server$Target extends UiSession$Server$Target {
  get(params: WebSession_Get$Params, results: Response): $.MaybePromise<void | $.Init<Response>>;
}
export class WebSession$Server extends $.Server {
  readonly target: WebSession$Server$Target;
  constructor(target: WebSession$Server$Target) {
    super(target, [
      ...(UiSession$Client.methods as $.Method<$.Struct, $.Struct>[]).map((method) => ({
        ...method,
        impl: async (params: $.Struct, results: $.Struct) => {
          const targetMethod = target[method.methodName as keyof WebSession$Server$Target] as unknown as (params: $.Struct, results: $.Struct) => $.MaybePromise<void | $.Init<$.Struct>>;
          const value = await targetMethod.call(target, params, results);
          if (value !== undefined) {
            $.applyInit(results, value);
          }
        }
      })),
      {
        ...WebSession$Client.ownMethods[0],
        impl: async (params: WebSession_Get$Params, results: Response) => {
          const value = await target.get(params, results);
          if (value !== undefined) {
            Response._applyInit(results, value as $.Init<Response>);
          }
        }
      }
    ]);
    this.target = target;
  }
  client(): WebSession$Client {
    return new WebSession$Client(this);
  }
}
export class WebSession extends $.Interface {
  static readonly Client = WebSession$Client;
  static readonly Server = WebSession$Server;
  static readonly _capnp = {
    displayName: "WebSession",
    id: "90d73605e02f91bb",
    typeId: 0x90d73605e02f91bbn,
    typeIdHex: "90d73605e02f91bb",
    size: new $.ObjectSize(0, 0),
    methods: WebSession$Client.methods,
  };
  toString(): string { return "WebSession_" + super.toString(); }
}
export class Context extends $.Struct {
  static readonly _capnp = {
    displayName: "Context",
    id: "b26193c077cc23a3",
    typeId: 0xb26193c077cc23a3n,
    typeIdHex: "b26193c077cc23a3",
    size: new $.ObjectSize(0, 1),
    fields: [
      { name: "responseStream", codeOrder: 0, ordinal: 0, kind: "slot", offset: 0, type: { kind: "interface", typeId: 0xf8adf062f19cb829n, typeIdHex: "f8adf062f19cb829", displayName: "ByteStream" } }
    ] as const,
  };
  static _applyInit(target: Context, value: $.Init<Context>): void {
    const init = value;
    {
      const value = init["responseStream"];
      if (value !== undefined) {
        target.responseStream = value;
      }
    }
  }
  get responseStream(): ByteStream$Client {
    return new ByteStream$Client($.utils.getInterfaceClientOrNullAt(0, this));
  }
  get responseStreamOrNull(): ByteStream$Client | null {
    const client = $.Interface.fromPointer($.utils.getPointer(0, this))?.getClient() ?? null;
    return client === null ? null : new ByteStream$Client(client);
  }
  set responseStreamOrNull(value: ByteStream$Client | null) {
    if (value === null) {
      $.utils.erase($.utils.getPointer(0, this));
    }
    else {
      this.responseStream = value;
    }
  }
  set responseStream(value: ByteStream$Client) {
    $.utils.setInterfacePointer(this.segment.message.addCap(value.client), $.utils.getPointer(0, this));
  }
  toString(): string { return "Context_" + super.toString(); }
}
